-- Seed word bank with words from the word list
-- Run this in Supabase SQL Editor. Uses ON CONFLICT to skip words that already exist.

INSERT INTO vocab_words (word, definition, root, origin, year_group, learning_point, synonyms, antonyms, example, letter_strings)
VALUES
  ('abandon', 'To leave behind or give up completely.', 'bandon', 'Latin', 'Year 5', 'Prefix a- (from Latin ab-)', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('abode', 'A place where someone lives; a home.', 'bide', 'Old English', 'Year 5', 'Letter string -ode', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('absence', 'The state of being away or not present.', 'absent', 'Latin', 'Year 5', '-ence suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('absurd', 'Completely unreasonable or silly.', 'surdus', 'Latin', 'Year 5', 'Latin root', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('abundance', 'A very large amount; plenty.', 'abundare', 'Latin', 'Year 5', '-ance suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('abundant', 'Existing in large amounts; plentiful.', 'abundare', 'Latin', 'Year 5', '-ant suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('accuse', 'To say someone has done something wrong.', 'causa', 'Latin', 'Year 4', 'Prefix ac-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('accustom', 'To make familiar through use or habit.', 'custom', 'Old French', 'Year 5', 'Prefix ac-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('acquainted', 'Familiar with or known to.', 'cognoscere', 'Latin', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('acquire', 'To get or gain something.', 'quaerere', 'Latin', 'Year 5', 'Letter string -quire', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('across', 'From one side to the other.', 'cross', 'Old English', 'Year 4', 'Prefix a-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('address', 'To speak to; or the details of where someone lives.', 'directus', 'Latin', 'Year 4', 'Double consonant -ss', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('adhere', 'To stick firmly to something.', 'haerere', 'Latin', 'Year 5', 'Prefix ad-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('admission', 'Permission to enter; or admitting something is true.', 'mittere', 'Latin', 'Year 5', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('adopt', 'To take up or choose to use.', 'optare', 'Latin', 'Year 5', 'Prefix ad-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('advance', 'To move forward or improve.', 'abante', 'Latin', 'Year 5', 'Letter string -ance', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('affable', 'Friendly and easy to talk to.', 'fari', 'Latin', 'Year 6', 'Prefix af-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('affectionate', 'Showing love or warmth.', 'affectio', 'Latin', 'Year 5', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('aid', 'Help or support.', 'adjuvare', 'Latin', 'Year 4', 'Short vowel pattern', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('alert', 'Quick to notice; a warning.', 'alertus', 'Italian', 'Year 4', 'Letter string -ert', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('all right', 'Satisfactory; okay.', 'all + right', 'Old English', 'Year 4', 'Two-word phrase', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ally', 'A person or country that helps or supports another.', 'allier', 'French', 'Year 5', 'Double l, -y ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('altitude', 'Height above sea level.', 'altus', 'Latin', 'Year 5', '-itude suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ambition', 'A strong desire to achieve something.', 'ambire', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('amount', 'A quantity or total.', 'monter', 'French', 'Year 4', 'Letter string -ount', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ample', 'Enough or more than enough.', 'amplus', 'Latin', 'Year 5', 'Letter string -ple', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('antiquity', 'Ancient times; great age.', 'antiquus', 'Latin', 'Year 6', '-ity suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('anxious', 'Worried or nervous.', 'angere', 'Latin', 'Year 5', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('appeal', 'To make a serious request; or to be attractive.', 'appellare', 'Latin', 'Year 5', 'Double p', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('appearance', 'The way something looks; or the act of appearing.', 'apparere', 'Latin', 'Year 5', '-ance suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('apprehensive', 'Anxious or fearful about something.', 'prehendere', 'Latin', 'Year 6', '-ive suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('approve', 'To have a good opinion of; to agree to.', 'approbare', 'Latin', 'Year 5', 'Prefix ap-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('arduous', 'Involving great effort; difficult.', 'arduus', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('argument', 'A reason or set of reasons given.', 'arguere', 'Latin', 'Year 5', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('arouse', 'To stir up or awaken.', 'arouser', 'French', 'Year 5', 'Letter string -ouse', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('artful', 'Clever or cunning.', 'art', 'Latin', 'Year 5', '-ful suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('article', 'A piece of writing; or a particular item.', 'articulus', 'Latin', 'Year 4', '-cle suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('assemble', 'To gather together; to put together.', 'assimulare', 'Latin', 'Year 5', 'Prefix as-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('assiduous', 'Showing great care and effort.', 'assidere', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('assistance', 'Help or support.', 'assistere', 'Latin', 'Year 5', '-ance suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('asunder', 'Apart; into pieces.', 'sundrian', 'Old English', 'Year 6', 'Archaic vocabulary', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('attached', 'Joined or connected; fond of.', 'attacher', 'French', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('attempt', 'To try to do something.', 'attempter', 'French', 'Year 4', 'Prefix at-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('available', 'Able to be used or obtained.', 'valoir', 'French', 'Year 5', '-able suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('average', 'The usual amount or level.', 'avarie', 'Arabic', 'Year 5', '-age suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('avoid', 'To keep away from.', 'esvuidier', 'French', 'Year 4', 'Letter string -oid', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('avowed', 'Openly declared or admitted.', 'avouer', 'French', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('awkward', 'Clumsy; causing difficulty.', 'awk', 'Norse', 'Year 5', '-ward suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('banish', 'To send someone away as punishment.', 'banir', 'French', 'Year 5', '-ish suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bargain', 'An agreement; something bought cheaply.', 'bargaine', 'French', 'Year 5', 'Letter string -ain', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('barren', 'Unable to produce; empty.', 'barain', 'Old French', 'Year 6', 'Double r', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('beautiful', 'Pleasing to look at.', 'beauty', 'Latin', 'Year 4', '-ful suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('because', 'For the reason that.', 'by cause', 'English', 'Year 3', 'Compound word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('beck', 'A gesture or nod summoning someone.', 'becken', 'Old Norse', 'Year 5', 'Short vowel -eck', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('believe', 'To accept as true.', 'beleven', 'Old English', 'Year 3', 'Letter string -ieve', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('belligerent', 'Aggressive; at war.', 'bellum', 'Latin', 'Year 6', 'Latin root bell-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bemused', 'Puzzled or confused.', 'muse', 'French', 'Year 6', 'Prefix be-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('benefit', 'Advantage or good result.', 'bene facere', 'Latin', 'Year 5', 'Latin root bene-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('besieged', 'Surrounded by forces.', 'siege', 'French', 'Year 6', 'Prefix be-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('betray', 'To be disloyal; to reveal secretly.', 'tradere', 'Latin', 'Year 5', 'Prefix be-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bewildered', 'Very confused.', 'wild', 'Old English', 'Year 5', 'Prefix be-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bicycle', 'A vehicle with two wheels.', 'bi- + cycle', 'Latin/Greek', 'Year 4', 'Prefix bi-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('box', 'A container with straight sides.', 'pyxis', 'Greek', 'Year 3', 'Short vowel -ox', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('brief', 'Short in time or length.', 'brevis', 'Latin', 'Year 4', 'Letter string -ief', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('Britain', 'The island containing England, Scotland, Wales.', 'Britannia', 'Latin', 'Year 4', 'Proper noun', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('broad', 'Wide; covering a large area.', 'brad', 'Old English', 'Year 4', 'Letter string -oad', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bruise', 'An injury under the skin.', 'brisen', 'Old English', 'Year 4', 'Letter string -uise', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('brusque', 'Abrupt or blunt in manner.', 'brusco', 'Italian', 'Year 6', 'Letter string -que', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('burden', 'A heavy load; something difficult.', 'byrthen', 'Old English', 'Year 5', '-en suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('business', 'Trade or work; a company.', 'busy', 'Old English', 'Year 4', '-ness suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('calamity', 'A disaster.', 'calamitas', 'Latin', 'Year 6', '-ity suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('candidate', 'A person applying for a job or election.', 'candidatus', 'Latin', 'Year 5', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('careering', 'Moving at full speed.', 'car', 'Latin', 'Year 6', '-ing suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('category', 'A class or group.', 'kategoria', 'Greek', 'Year 5', '-ory suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('caulking', 'Sealing gaps with a filler.', 'calquer', 'French', 'Year 6', '-ing suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('caution', 'Care to avoid danger.', 'cautio', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cease', 'To stop.', 'cesser', 'Latin', 'Year 5', 'Letter string -ease', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cemetery', 'A place where dead people are buried.', 'koimeterion', 'Greek', 'Year 5', 'Letter string -ery', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('chaos', 'Complete disorder.', 'khaos', 'Greek', 'Year 5', 'Greek origin', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('charred', 'Burned to charcoal.', 'char', 'Unknown', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('choreographer', 'A person who designs dances.', 'choros + graph', 'Greek', 'Year 6', '-er suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('clemency', 'Mercy or leniency.', 'clementia', 'Latin', 'Year 6', '-cy suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('coarse', 'Rough; not fine.', 'cors', 'Latin', 'Year 5', 'Letter string -arse', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('coax', 'To persuade gently.', 'cokes', 'Unknown', 'Year 5', 'Letter string -oax', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('college', 'A place of higher education.', 'collegium', 'Latin', 'Year 4', '-lege ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('colour', 'The appearance of things from light.', 'color', 'Latin', 'Year 3', 'UK spelling -our', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('combination', 'A mix or joining.', 'combinare', 'Latin', 'Year 5', '-ation suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('commence', 'To begin.', 'commencer', 'French', 'Year 5', 'Prefix com-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('commit', 'To do something; to pledge.', 'committere', 'Latin', 'Year 5', 'Prefix com-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('communicate', 'To share information.', 'communicare', 'Latin', 'Year 5', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('community', 'A group of people living together.', 'communitas', 'Latin', 'Year 4', '-ity suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('companion', 'A person who accompanies another.', 'companio', 'Latin', 'Year 5', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('company', 'A business; or companionship.', 'companion', 'Latin', 'Year 4', 'Letter string -any', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('compel', 'To force someone to do something.', 'compellere', 'Latin', 'Year 6', 'Prefix com-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('competition', 'An event to see who is best.', 'competere', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('completely', 'Totally; in every way.', 'complete', 'Latin', 'Year 4', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('complex', 'Complicated; made of many parts.', 'complexus', 'Latin', 'Year 5', 'Letter string -ex', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('composition', 'Something made by combining parts; a piece of writing.', 'componere', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('comprehend', 'To understand fully.', 'comprehendere', 'Latin', 'Year 6', 'Prefix com-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('contribute', 'To give something towards a cause.', 'contribuere', 'Latin', 'Year 5', '-ute suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}')
ON CONFLICT (word) DO NOTHING;
