-- High-frequency words: Fourth 100 through Ninth 100 (no duplicates).
-- Run in Supabase SQL Editor. ON CONFLICT (word) DO NOTHING skips words already in the word bank.

INSERT INTO vocab_words (word, definition, root, origin, year_group, learning_point, synonyms, antonyms, example, letter_strings)
VALUES
  ('body', 'The physical structure of a person or animal.', 'bodig', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('music', 'Sounds arranged in a pleasing way.', 'musica', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('color', 'The appearance of things from light (US spelling).', 'color', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stand', 'To be on your feet; to tolerate.', 'standan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sun', 'The star that gives daylight.', 'sunne', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('questions', 'Things asked to find out something.', 'quaestio', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fish', 'An animal that lives in water.', 'fisc', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('area', 'A region or space.', 'area', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mark', 'A spot or sign; to make a sign.', 'mearc', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dog', 'A four-legged animal often kept as a pet.', 'docga', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('horse', 'A large animal used for riding.', 'hors', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('birds', 'Animals with feathers and wings.', 'brid', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('problem', 'Something difficult to solve.', 'problema', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('complete', 'Having all parts; to finish.', 'completus', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('room', 'A space inside a building.', 'rum', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('knew', 'Past of know.', 'cnawan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('since', 'From a time in the past; because.', 'sith', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ever', 'At any time.', 'æfre', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('piece', 'A part of something.', 'pece', 'French', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('told', 'Past of tell.', 'tellan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('usually', 'Most of the time.', 'usual', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('didn''t', 'Did not.', 'did not', 'English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('friends', 'People who like each other.', 'freond', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('easy', 'Not difficult.', 'ease', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('heard', 'Past of hear.', 'hieran', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('order', 'A sequence; a request for goods.', 'ordre', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('red', 'The colour of blood.', 'read', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('door', 'An opening in a wall to go through.', 'duru', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sure', 'Certain; without doubt.', 'seur', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('become', 'To grow to be.', 'becuman', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('top', 'The highest part.', 'topp', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ship', 'A large boat.', 'scip', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('across', 'From one side to the other.', 'cross', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('today', 'This day.', 'to + day', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('during', 'Throughout a time.', 'durer', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('short', 'Not long.', 'sceort', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('better', 'Of higher quality.', 'bet', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('best', 'Of the highest quality.', 'betst', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('however', 'Nevertheless; in whatever way.', 'how + ever', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('low', 'Near the ground; not high.', 'lah', 'Old Norse', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hours', 'Units of time (60 minutes).', 'hour', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('black', 'The darkest colour.', 'blæc', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('products', 'Things that are made or grown.', 'productum', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('happened', 'Past of happen.', 'happen', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('whole', 'Complete; all of something.', 'hal', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('measure', 'To find the size or amount.', 'mensura', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('remember', 'To keep in mind.', 'rememorari', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('early', 'Before the usual time.', 'ærlice', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('waves', 'Rises of water; movements.', 'wafian', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('reached', 'Past of reach.', 'ræcan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('listen', 'To pay attention to sound.', 'hlysnan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wind', 'Moving air.', 'wind', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rock', 'A large stone; to move gently.', 'rocc', 'Old French', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('space', 'Empty area; outer space.', 'spatium', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('covered', 'Past of cover; having a lid or layer.', 'cooperire', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fast', 'Quick; firmly.', 'fæst', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('several', 'More than two but not many.', 'several', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hold', 'To grasp; to contain.', 'healdan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('himself', 'Reflexive form of him.', 'him + self', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('toward', 'In the direction of.', 'toward', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('five', 'The number 5.', 'fif', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('step', 'A movement of the foot; a stage.', 'stæpe', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('morning', 'The early part of the day.', 'morgen', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('passed', 'Past of pass.', 'passen', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('vowel', 'A sound represented by a, e, i, o, u.', 'vocalis', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('true', 'Correct; real.', 'treowe', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hundred', 'The number 100.', 'hund', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('against', 'In opposition to.', 'agen', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pattern', 'A repeated design or sequence.', 'patron', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('numeral', 'A symbol for a number.', 'numerus', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('table', 'A piece of furniture; a chart.', 'tabula', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('north', 'The direction towards the pole.', 'norð', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('slowly', 'At a low speed.', 'slow', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('money', 'Coins and notes used to buy things.', 'moneta', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('map', 'A drawing of an area.', 'mappa', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('farm', 'Land for growing crops or raising animals.', 'feorm', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pulled', 'Past of pull.', 'pullian', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('draw', 'To make a picture; to pull.', 'drawen', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('voice', 'Sound made when speaking.', 'voix', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('seen', 'Past participle of see.', 'seon', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cold', 'Low in temperature.', 'ceald', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cried', 'Past of cry.', 'crian', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('plan', 'A way to do something; to intend.', 'plan', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('notice', 'To see; a sign or warning.', 'notitia', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('south', 'The direction opposite north.', 'suð', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sing', 'To make music with the voice.', 'singan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('war', 'Fighting between countries or groups.', 'werre', 'French', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ground', 'The surface of the earth.', 'grund', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fall', 'To drop down; autumn.', 'feallan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('king', 'A male ruler of a country.', 'cyning', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('town', 'A place with buildings, smaller than a city.', 'tun', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('I''ll', 'I will.', 'I will', 'English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('unit', 'A single thing; a measure.', 'unitas', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('figure', 'A number; a shape; a person.', 'figura', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('certain', 'Sure; particular.', 'certus', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('field', 'An area of open land.', 'feld', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('travel', 'To go from place to place.', 'travail', 'French', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wood', 'The material trees are made of.', 'wudu', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fire', 'Flames and heat.', 'fyr', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('upon', 'On.', 'uppon', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('done', 'Past participle of do; finished.', 'don', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('English', 'The language of England.', 'Englisc', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('road', 'A path for vehicles.', 'rad', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('half', 'One of two equal parts.', 'healf', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ten', 'The number 10.', 'tien', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fly', 'To move through the air.', 'fleogan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('gave', 'Past of give.', 'giefan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('box', 'A container with straight sides.', 'pyxis', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('finally', 'At the end; after a long time.', 'final', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wait', 'To stay until something happens.', 'waiten', 'French', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('correct', 'Right; without mistakes.', 'correctus', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('oh', 'Used to express surprise or other feeling.', 'o', 'Unknown', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('quickly', 'At high speed.', 'quick', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('person', 'A human being.', 'persona', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('became', 'Past of become.', 'becuman', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('shown', 'Past participle of show.', 'sceawian', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('minutes', 'Units of time (60 seconds).', 'minuta', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('strong', 'Having great power.', 'strang', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('verb', 'A word that describes an action.', 'verbum', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stars', 'Bright objects in the night sky.', 'steorra', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('front', 'The forward part.', 'frons', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('feel', 'To sense by touch or emotion.', 'felan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fact', 'Something that is true.', 'factum', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inches', 'Units of length.', 'uncia', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('street', 'A road in a town with buildings.', 'stræt', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('decided', 'Past of decide.', 'decidere', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('contain', 'To hold within.', 'continere', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('course', 'A path; a series of lessons.', 'cursus', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('surface', 'The outside or top of something.', 'superficies', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('produce', 'To make or grow.', 'producere', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('building', 'A structure with walls and a roof.', 'byldan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ocean', 'A very large area of salt water.', 'oceanus', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('class', 'A group of students; a category.', 'classis', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('note', 'A short message; a musical sound.', 'nota', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('nothing', 'Not anything.', 'nathing', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rest', 'To relax; what is left.', 'rest', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('carefully', 'In a careful way.', 'care', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('scientists', 'People who study science.', 'scientia', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inside', 'Within; the inner part.', 'innan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wheels', 'Round parts that turn.', 'hweol', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stay', 'To remain in a place.', 'estai', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('green', 'The colour of grass.', 'grene', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('known', 'Past participle of know.', 'cnawan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('island', 'Land surrounded by water.', 'igland', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('week', 'Seven days.', 'wice', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('less', 'A smaller amount.', 'læs', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('machine', 'A device that does work.', 'machina', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('base', 'The bottom; a starting point.', 'basis', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ago', 'In the past.', 'agon', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stood', 'Past of stand.', 'standan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('plane', 'An aircraft; a flat surface.', 'planum', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('system', 'A set of parts working together.', 'systema', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('behind', 'At the back of.', 'behindan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ran', 'Past of run.', 'rinnan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('round', 'Shaped like a circle; around.', 'round', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('boat', 'A small vessel for water.', 'bat', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('game', 'A playful activity; a sport.', 'gamen', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('force', 'Strength; to make something happen.', 'force', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('brought', 'Past of bring.', 'bringan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('understand', 'To grasp the meaning.', 'understandan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('warm', 'Having a comfortable heat.', 'wearm', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('common', 'Shared; ordinary.', 'communis', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bring', 'To carry towards.', 'bringan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('explain', 'To make clear.', 'explanare', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dry', 'Without moisture.', 'dryge', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('though', 'Although; however.', 'theah', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('language', 'Words used to communicate.', 'lingua', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('shape', 'The form of something.', 'scieppan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('deep', 'Going far down.', 'deop', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('thousands', 'Many thousands.', 'thusend', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('yes', 'Used to agree.', 'gise', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('clear', 'Easy to see or understand.', 'cler', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('equation', 'A statement that two things are equal.', 'aequatio', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('yet', 'Up to now; but.', 'giet', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('government', 'The system that runs a country.', 'gubernare', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('filled', 'Made full.', 'fyllan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('heat', 'Hotness; to make hot.', 'hætu', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('full', 'Containing as much as possible.', 'full', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hot', 'Having high temperature.', 'hat', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('check', 'To examine; a pattern of squares.', 'chek', 'Persian', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('object', 'A thing; to disagree.', 'obicere', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rule', 'A law or guideline.', 'regula', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('among', 'In the middle of.', 'on gemang', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('noun', 'A word for a person, place, or thing.', 'nomen', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('power', 'Strength; ability to do something.', 'pouvoir', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cannot', 'Can not.', 'can + not', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('able', 'Having the ability.', 'habilis', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('six', 'The number 6.', 'siex', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('size', 'How big something is.', 'sise', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dark', 'With little or no light.', 'deorc', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ball', 'A round object used in games.', 'ball', 'Old Norse', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('material', 'What something is made of.', 'materia', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('special', 'Different from usual; important.', 'specialis', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('heavy', 'Having great weight.', 'hefig', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fine', 'Very good; thin.', 'fin', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pair', 'Two things that go together.', 'pair', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('circle', 'A round shape.', 'circulus', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('include', 'To contain as part of.', 'includere', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('built', 'Past of build.', 'byldan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}')
ON CONFLICT (word) DO NOTHING;

INSERT INTO vocab_words (word, definition, root, origin, year_group, learning_point, synonyms, antonyms, example, letter_strings)
VALUES
  ('can''t', 'Cannot.', 'can not', 'English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('matter', 'Physical substance; to be important.', 'materia', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('square', 'A shape with four equal sides.', 'exquadrare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('syllables', 'Units of sound in a word.', 'syllaba', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('perhaps', 'Maybe.', 'per hap', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bill', 'A piece of paper money; a beak.', 'billa', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('felt', 'Past of feel; a type of cloth.', 'felt', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('suddenly', 'Without warning.', 'soden', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('test', 'To check; an examination.', 'testum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('direction', 'The way something points or goes.', 'directio', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('center', 'The middle (US spelling).', 'centrum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('farmers', 'People who work on farms.', 'farm', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ready', 'Prepared.', 'ræde', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('anything', 'Any thing at all.', 'any + thing', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('divided', 'Split into parts.', 'dividere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('general', 'Widespread; not specific.', 'generalis', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('energy', 'The ability to do work.', 'energia', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('subject', 'A topic; a person under rule.', 'subjectus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('Europe', 'The continent.', 'Europa', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('moon', 'The object that orbits Earth at night.', 'mona', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('region', 'An area.', 'regio', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('return', 'To come or go back.', 'returner', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('believe', 'To accept as true.', 'beleven', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dance', 'To move to music.', 'danser', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('members', 'People in a group.', 'membrum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('picked', 'Past of pick.', 'pician', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('simple', 'Easy; not complicated.', 'simplus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cells', 'Small rooms; basic units of life.', 'cella', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('paint', 'Coloured liquid for coating; to apply it.', 'peindre', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mind', 'The brain; to object.', 'gemynd', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('love', 'Strong affection.', 'lufu', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cause', 'To make happen; a reason.', 'causa', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rain', 'Water falling from clouds.', 'regn', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('exercise', 'Physical activity; practice.', 'exercitium', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('eggs', 'Oval objects laid by birds.', 'æg', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('train', 'A railway vehicle; to teach.', 'train', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('blue', 'A colour like the sky.', 'blaw', 'German', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wish', 'To want; a desire.', 'wyscan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('drop', 'A small amount of liquid; to fall.', 'dropa', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('developed', 'Grew or advanced.', 'developer', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('window', 'An opening in a wall with glass.', 'vindauga', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('difference', 'The way things are not the same.', 'differentia', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('distance', 'The space between two points.', 'distantia', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('heart', 'The organ that pumps blood.', 'heorte', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('site', 'A location.', 'situs', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sum', 'The total from adding.', 'summa', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('summer', 'The warm season.', 'sumor', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wall', 'A vertical structure.', 'weall', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('forest', 'A large area of trees.', 'forest', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('probably', 'Almost certainly.', 'probabilis', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('legs', 'Limbs used for standing and walking.', 'leg', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sat', 'Past of sit.', 'sittan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('main', 'Most important.', 'magen', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('winter', 'The cold season.', 'winter', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wide', 'Measuring a lot from side to side.', 'wid', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('written', 'Past participle of write.', 'writan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('length', 'How long something is.', 'length', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('reason', 'A cause; to think logically.', 'ratio', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('kept', 'Past of keep.', 'cepan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('interest', 'Curiosity; money paid for a loan.', 'interest', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('arms', 'Limbs from shoulder to hand; weapons.', 'arm', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('brother', 'A male sibling.', 'brothor', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('race', 'A competition of speed; a group of people.', 'ras', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('present', 'Here now; a gift; to give.', 'praesens', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('beautiful', 'Pleasing to look at.', 'beauty', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('store', 'A shop; to keep for later.', 'stor', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('job', 'Work that you are paid for.', 'jobbe', 'Unknown', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('edge', 'The border or limit.', 'ecg', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('past', 'Gone by; previous time.', 'past', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sign', 'A notice or symbol.', 'signum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('record', 'To write down; the best performance.', 'recordari', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('finished', 'Completed.', 'finir', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('discovered', 'Found for the first time.', 'discooperire', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wild', 'Not tame; not cultivated.', 'wilde', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('happy', 'Feeling pleasure.', 'hap', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('beside', 'Next to.', 'be sidan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('gone', 'Past participle of go.', 'gan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sky', 'The space above the earth.', 'sky', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('grass', 'Green plants that cover the ground.', 'gras', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('million', 'One thousand thousands.', 'million', 'Italian', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('clothes', 'Things worn on the body.', 'clath', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('flowers', 'Coloured parts of plants.', 'flor', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('shall', 'Used for future (I/we).', 'sceal', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('teacher', 'A person who teaches.', 'tæcan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('held', 'Past of hold.', 'healdan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('describe', 'To say what something is like.', 'describere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('drive', 'To operate a vehicle; to push.', 'drifan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('taken', 'Past participle of take.', 'tacan', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('volume', 'Amount of space; loudness.', 'volumen', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bank', 'The edge of a river; a place for money.', 'bank', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('collect', 'To gather together.', 'collectus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('save', 'To keep safe; to rescue.', 'sauver', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('control', 'Power over; to manage.', 'contrarotulum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('decimal', 'Based on ten.', 'decimalis', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('gentle', 'Soft; kind.', 'gentil', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('woman', 'An adult female.', 'wifman', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('captain', 'The leader of a ship or team.', 'capitaneus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('direct', 'Straight; to manage.', 'directus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ring', 'A circular band; a sound.', 'hring', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('serve', 'To work for; to give food.', 'servire', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cross', 'To go across; angry.', 'cros', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('speak', 'To say words.', 'specan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('solve', 'To find an answer.', 'solvere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('appear', 'To become visible.', 'apparere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('metal', 'A hard material like iron.', 'metallum', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('son', 'A male child.', 'sunu', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('either', 'One of two.', 'ægther', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ice', 'Frozen water.', 'is', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sleep', 'To rest with eyes closed.', 'slæp', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('village', 'A small community.', 'village', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('factors', 'Things that contribute to a result.', 'factor', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('result', 'What happens because of something.', 'resultare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('jumped', 'Past of jump.', 'jump', 'Unknown', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('snow', 'Frozen rain.', 'snaw', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ride', 'To travel on or in.', 'ridan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('care', 'Attention; worry.', 'caru', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('floor', 'The bottom surface of a room.', 'flor', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hill', 'A raised area of land.', 'hyll', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pushed', 'Past of push.', 'pushen', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('baby', 'A very young child.', 'babe', 'Unknown', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('buy', 'To get by paying.', 'bycgan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('century', 'A period of 100 years.', 'centuria', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('outside', 'The external part.', 'ut + side', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('everything', 'All things.', 'every + thing', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tall', 'Having great height.', 'getæl', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('already', 'Before now.', 'all + ready', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('instead', 'As an alternative.', 'in + stead', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('phrase', 'A group of words.', 'phrasis', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('soil', 'The top layer of earth.', 'soil', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bed', 'A piece of furniture for sleeping.', 'bedd', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('copy', 'To make the same; a duplicate.', 'copia', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('free', 'Not costing money; not trapped.', 'freo', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hope', 'To want something to happen.', 'hopa', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('spring', 'The season after winter; a leap.', 'springan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('case', 'A situation; a container.', 'casus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('laughed', 'Past of laugh.', 'hliehhan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('nation', 'A country or people.', 'nation', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('quite', 'Completely; to a degree.', 'quit', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('type', 'A kind; to write on a keyboard.', 'typus', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('themselves', 'Reflexive form of they.', 'them + self', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('temperature', 'How hot or cold something is.', 'temperatura', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bright', 'Giving out light; clever.', 'beorht', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lead', 'To guide; a metal.', 'lædan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('everyone', 'Every person.', 'every + one', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('method', 'A way of doing something.', 'methodus', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('section', 'A part of something.', 'sectio', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lake', 'A large body of water on land.', 'lac', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('iron', 'A strong metal.', 'iren', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('within', 'Inside.', 'withinne', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dictionary', 'A book that explains words.', 'dictionarium', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hair', 'Threads growing from the head.', 'hær', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('age', 'How old someone or something is.', 'aage', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('amount', 'A quantity.', 'amonter', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('scale', 'A series of levels; to climb.', 'scala', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pounds', 'Units of weight; British money.', 'pund', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('although', 'Even though.', 'all + though', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('per', 'For each.', 'per', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('broken', 'Past participle of break; damaged.', 'brecan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('moment', 'A very short time.', 'momentum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tiny', 'Very small.', 'tine', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('possible', 'Able to happen.', 'possibilis', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}')
ON CONFLICT (word) DO NOTHING;

INSERT INTO vocab_words (word, definition, root, origin, year_group, learning_point, synonyms, antonyms, example, letter_strings)
VALUES
  ('gold', 'A precious yellow metal.', 'gold', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('milk', 'White liquid from cows.', 'meoluc', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('quiet', 'Making little noise.', 'quietus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('natural', 'From nature; not made by people.', 'naturalis', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lot', 'A large amount; a piece of land.', 'hlot', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stone', 'A piece of rock.', 'stan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('act', 'To do something; a deed.', 'actus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('build', 'To make by putting parts together.', 'byldan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('middle', 'The center part.', 'midel', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('speed', 'How fast something moves.', 'sped', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('count', 'To say numbers in order.', 'counten', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('consonant', 'A letter that is not a vowel.', 'consonans', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('someone', 'Some person.', 'some + one', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sail', 'To travel by boat; a piece of cloth.', 'segel', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rolled', 'Past of roll.', 'rollen', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bear', 'To carry; a large animal.', 'bera', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wonder', 'To want to know; amazement.', 'wundor', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('smiled', 'Past of smile.', 'smile', 'Unknown', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('angle', 'The space between two lines.', 'angulus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fraction', 'A part of a whole.', 'fractio', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('Africa', 'The continent.', 'Africa', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('killed', 'Past of kill.', 'cwellan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('melody', 'A tune.', 'melodia', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bottom', 'The lowest part.', 'botm', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('trip', 'A journey; to stumble.', 'trippen', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hole', 'An opening or hollow.', 'hol', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('poor', 'Having little money.', 'pauper', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('let''s', 'Let us.', 'let us', 'English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fight', 'To struggle against.', 'feohtan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('surprise', 'An unexpected event.', 'surprendre', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('French', 'From or relating to France.', 'Franc', 'German', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('died', 'Past of die.', 'dead', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('beat', 'To hit; to defeat.', 'beatan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('exactly', 'Precisely.', 'exact', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('remain', 'To stay behind.', 'remanere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dress', 'Clothing; to put on clothes.', 'dresser', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('couldn''t', 'Could not.', 'could not', 'English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fingers', 'Digits on the hand.', 'finger', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('row', 'A line; to move a boat with oars.', 'raw', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('least', 'Smallest amount.', 'læst', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('catch', 'To seize; to get.', 'cacchen', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('climbed', 'Past of climb.', 'climban', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wrote', 'Past of write.', 'writan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('shouted', 'Past of shout.', 'shout', 'Unknown', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('continued', 'Kept going.', 'continuer', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('itself', 'Reflexive form of it.', 'it + self', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('else', 'Other; different.', 'elles', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('plains', 'Flat areas of land.', 'plain', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('gas', 'A substance like air.', 'chaos', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('England', 'A country in Britain.', 'Englaland', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('burning', 'On fire.', 'byrnan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('design', 'A plan; to plan.', 'designare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('joined', 'Past of join.', 'joindre', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('foot', 'The end of the leg.', 'fot', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('law', 'A rule that must be followed.', 'lagu', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ears', 'Organs for hearing.', 'eare', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('glass', 'A hard transparent material.', 'glæs', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('you''re', 'You are.', 'you are', 'English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('grew', 'Past of grow.', 'growan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('skin', 'The outer layer of the body.', 'skinn', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('valley', 'Low land between hills.', 'val', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cents', 'Units of money.', 'centum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('symbols', 'Signs that stand for something.', 'symbolum', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wear', 'To have on the body.', 'werian', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bad', 'Not good; of poor quality.', 'bæddel', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('experiment', 'A test to discover something.', 'experimentum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('engine', 'A machine that provides power.', 'engin', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('alone', 'Without others.', 'all + one', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('drawing', 'A picture made with pencil etc.', 'draw', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('east', 'The direction of the sunrise.', 'east', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('choose', 'To pick.', 'ceosan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('single', 'One only.', 'singulus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('touch', 'To feel with the hand.', 'toucher', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('information', 'Facts or details.', 'informatio', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('express', 'To show; fast.', 'expressus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mouth', 'The opening for eating and speaking.', 'muð', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('yard', 'An area outside a building; a unit of length.', 'geard', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('equal', 'The same in amount or value.', 'aequalis', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('yourself', 'Reflexive form of you.', 'you + self', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('practice', 'To do repeatedly to improve.', 'practicare', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('report', 'To tell about; a written account.', 'reportare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('straight', 'Not curved.', 'streht', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rise', 'To go up.', 'risan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('statement', 'Something stated.', 'statement', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stick', 'A thin piece of wood; to attach.', 'sticca', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('party', 'A social gathering; a group.', 'partie', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('seeds', 'What plants grow from.', 'sæd', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('suppose', 'To assume.', 'supposer', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('coast', 'Where land meets the sea.', 'costa', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('period', 'A length of time; a full stop.', 'periodus', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wire', 'A thin piece of metal.', 'wir', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pay', 'To give money for.', 'paier', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('clean', 'Not dirty; to make clean.', 'clæne', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('visit', 'To go to see.', 'visiter', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bit', 'A small piece.', 'bita', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('whose', 'Belonging to whom.', 'hwæs', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('received', 'Past of receive.', 'recipere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('garden', 'Land for growing plants.', 'geard', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('please', 'To make happy; polite word.', 'plaire', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('strange', 'Unusual; not familiar.', 'estrange', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('caught', 'Past of catch.', 'cacchen', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fell', 'Past of fall.', 'feallan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('team', 'A group working together.', 'team', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('God', 'The supreme being (in religion).', 'god', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('child', 'A young person.', 'cild', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('desert', 'Dry land with little rain.', 'desertus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('increase', 'To become greater.', 'increscere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('history', 'Events of the past.', 'historia', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cost', 'The price; to have as price.', 'cost', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('maybe', 'Perhaps.', 'may + be', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('business', 'Trade or work.', 'busy', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('separate', 'To divide; not together.', 'separare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('break', 'To separate into pieces.', 'brecan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('uncle', 'Brother of your parent.', 'uncle', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hunting', 'Chasing animals for food or sport.', 'hunt', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('flow', 'To move like a liquid.', 'flowan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lady', 'A woman.', 'hlæfdige', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('students', 'People who are learning.', 'studere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('human', 'A person.', 'humanus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('art', 'Painting, sculpture, etc.', 'ars', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('feeling', 'An emotion.', 'felan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('made', 'Past of make.', 'macian', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mountain', 'A very high hill.', 'mont', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('supply', 'To provide; an amount available.', 'supplier', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('corner', 'Where two edges meet.', 'cornere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('electric', 'Using electricity.', 'electricus', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('insects', 'Small animals with six legs.', 'insectum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('crops', 'Plants grown for food.', 'crop', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tone', 'A sound; a mood.', 'tonus', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hit', 'To strike.', 'hittan', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sand', 'Tiny grains of rock.', 'sand', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('doctor', 'A person who treats the sick.', 'doctor', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('provide', 'To supply.', 'providere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('thus', 'In this way.', 'thus', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('won''t', 'Will not.', 'will not', 'English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cook', 'To prepare food; a person who cooks.', 'coc', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bones', 'Hard parts inside the body.', 'ban', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mall', 'A large indoor shopping area.', 'mall', 'Unknown', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('board', 'A flat piece of wood; to get on.', 'bord', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('addition', 'Something added; the operation +.', 'additio', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('belong', 'To be part of.', 'belangen', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('safe', 'Free from danger.', 'sauf', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('soldiers', 'People in an army.', 'soldier', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('guess', 'To estimate without knowing.', 'gessen', 'Unknown', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('silent', 'Making no sound.', 'silens', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('trade', 'Buying and selling.', 'trad', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rather', 'Preferably; quite.', 'hrathor', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('compare', 'To look at similarities.', 'comparare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('crowd', 'A large group of people.', 'crud', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('poem', 'A piece of writing in verse.', 'poema', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('enjoy', 'To take pleasure in.', 'enjoier', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('elements', 'Basic parts.', 'elementum', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('indicate', 'To point out.', 'indicare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('except', 'Not including.', 'excipere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('expect', 'To think something will happen.', 'expectare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('flat', 'Level; not curved.', 'flat', 'Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('seven', 'The number 7.', 'seofon', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('interesting', 'Holding attention.', 'interest', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sense', 'A meaning; to perceive.', 'sensus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('string', 'Thin rope; a series.', 'streng', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('blow', 'To move air; a hit.', 'blawan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('famous', 'Well known.', 'famosus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('value', 'Worth; importance.', 'valoir', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wings', 'Parts used for flying.', 'wenge', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('movement', 'The act of moving.', 'movement', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pole', 'A long stick; the ends of the earth.', 'pal', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('exciting', 'Causing excitement.', 'excite', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('glance', 'A quick look.', 'glancer', 'French', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('branches', 'Parts of a tree that grow from the trunk.', 'branch', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('thick', 'Wide; dense.', 'thicc', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('blood', 'The red liquid in the body.', 'blod', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lie', 'To say something untrue; to recline.', 'leogan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('spot', 'A mark; a place.', 'spot', 'Unknown', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('loud', 'Making a lot of noise.', 'hlud', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('consider', 'To think about.', 'considerare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('suggested', 'Past of suggest.', 'suggerere', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('thin', 'Not thick.', 'thynne', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('position', 'A place or rank.', 'positio', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('entered', 'Past of enter.', 'entrer', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fruit', 'The edible part of a plant.', 'fructus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tied', 'Past of tie.', 'tigan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rich', 'Having a lot of money.', 'rice', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dollars', 'Units of money.', 'dollar', 'German', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('send', 'To cause to go.', 'sendan', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sight', 'The ability to see; a view.', 'siht', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('chief', 'Most important; a leader.', 'chef', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('Japanese', 'From or relating to Japan.', 'Japan', 'Unknown', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stream', 'A small river.', 'stream', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('planets', 'Bodies that orbit a star.', 'planeta', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rhythm', 'A pattern of beats.', 'rhythmus', 'Greek', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('eight', 'The number 8.', 'eahta', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('science', 'The study of the natural world.', 'scientia', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('major', 'Very important; main.', 'major', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('observe', 'To watch carefully.', 'observare', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tube', 'A long hollow cylinder.', 'tube', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('necessary', 'Required; needed.', 'necessarius', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('weight', 'How heavy something is.', 'gewicht', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('meat', 'Animal flesh as food.', 'mete', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lifted', 'Past of lift.', 'lyft', 'Old Norse', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('process', 'A series of steps.', 'processus', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('army', 'A large group of soldiers.', 'armee', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hat', 'A covering for the head.', 'hætt', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('property', 'Something owned; a quality.', 'proprietas', 'Latin', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('bird', 'An animal with feathers and wings.', 'brid', 'Old English', 'Year 6', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}')
ON CONFLICT (word) DO NOTHING;
