-- Seed word bank with words from Page 3+ of the word list (no duplicates).
-- Run this in Supabase SQL Editor. Uses ON CONFLICT to skip words that already exist.

INSERT INTO vocab_words (word, definition, root, origin, year_group, learning_point, synonyms, antonyms, example, letter_strings)
VALUES
  ('government', 'The system of leaders and rules that run a country.', 'gubernare', 'Latin', 'Year 5', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('grate', 'To shred; or a framework of bars.', 'cratis', 'Latin', 'Year 5', 'Letter string -ate', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('gratitude', 'Thankfulness for something given or done.', 'gratus', 'Latin', 'Year 5', '-itude suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('grave', 'Serious; or a place of burial.', 'gravis', 'Latin', 'Year 5', 'Letter string -ave', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('gregarious', 'Enjoying being in groups; sociable.', 'grex', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('grieve', 'To feel deep sadness.', 'gravare', 'Latin', 'Year 5', 'Letter string -ieve', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('grotesque', 'Very ugly or strange in an unpleasant way.', 'grottesco', 'Italian', 'Year 6', '-esque suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('guarantee', 'A promise that something will happen or work.', 'garantir', 'French', 'Year 5', 'Letter string -antee', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('guard', 'To protect; a person who protects.', 'guarder', 'French', 'Year 4', 'Letter string -uard', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('habitable', 'Suitable to live in.', 'habitare', 'Latin', 'Year 6', '-able suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('habitat', 'The natural home of an animal or plant.', 'habitare', 'Latin', 'Year 5', '-at suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('halt', 'To stop.', 'halten', 'German', 'Year 5', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('handkerchief', 'A square of cloth for wiping nose or face.', 'hand + kerchief', 'English', 'Year 5', 'Silent d', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hasty', 'Done too quickly; rushed.', 'hastif', 'French', 'Year 5', '-y suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('helix', 'A spiral shape.', 'helix', 'Greek', 'Year 6', 'Greek origin', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('heroic', 'Very brave; like a hero.', 'heros', 'Greek', 'Year 5', '-ic suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hoax', 'A trick meant to deceive.', 'hocus', 'Unknown', 'Year 6', 'Letter string -oax', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('holiday', 'A day of rest or celebration.', 'holy + day', 'Old English', 'Year 4', 'Compound word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hollow', 'Empty inside; a hole or valley.', 'holh', 'Old English', 'Year 5', 'Double l', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('humble', 'Modest; not proud.', 'humilis', 'Latin', 'Year 5', 'Letter string -ble', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hygienic', 'Clean and free from germs.', 'hygieinos', 'Greek', 'Year 6', '-ic suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('idiosyncrasy', 'A strange or unusual habit that makes someone different.', 'idios + synkrasis', 'Greek', 'Year 6', 'Greek compound', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('idle', 'Not working; lazy.', 'idel', 'Old English', 'Year 5', 'Letter string -dle', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('idol', 'Someone or something greatly admired.', 'eidolon', 'Greek', 'Year 5', 'Letter string -ol', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ignorant', 'Lacking knowledge.', 'ignorare', 'Latin', 'Year 5', '-ant suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('imitate', 'To copy or mimic.', 'imitari', 'Latin', 'Year 5', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('immediate', 'Happening at once.', 'immediatus', 'Latin', 'Year 5', 'Prefix im-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('immediately', 'At once; without delay.', 'immediate', 'Latin', 'Year 5', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('immerse', 'To dip or plunge fully into.', 'immersus', 'Latin', 'Year 6', 'Prefix im-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('impudent', 'Rude or disrespectful.', 'impudens', 'Latin', 'Year 6', '-ent suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('in between', 'In the space that separates two things.', 'between', 'Old English', 'Year 4', 'Two-word phrase', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('in fact', 'Actually; in reality.', 'fact', 'Latin', 'Year 4', 'Two-word phrase', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('in front', 'In a position ahead.', 'front', 'Latin', 'Year 4', 'Two-word phrase', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inaudible', 'Unable to be heard.', 'audire', 'Latin', 'Year 6', 'Prefix in-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inaugural', 'Marking a beginning.', 'inaugurare', 'Latin', 'Year 6', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inaugurate', 'To begin or open formally.', 'inaugurare', 'Latin', 'Year 6', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('incision', 'A cut made in something.', 'incidere', 'Latin', 'Year 6', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inconspicuous', 'Not easily noticed.', 'conspicere', 'Latin', 'Year 6', 'Prefix in-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('individual', 'Single; one person or thing.', 'individuus', 'Latin', 'Year 5', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inedible', 'Not safe or fit to eat.', 'edibilis', 'Latin', 'Year 6', 'Prefix in-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inferior', 'Lower in quality or rank.', 'inferus', 'Latin', 'Year 6', '-ior suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('influence', 'The power to affect someone or something.', 'influere', 'Latin', 'Year 5', '-ence suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inhabit', 'To live in a place.', 'habitare', 'Latin', 'Year 5', 'Prefix in-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inhabitants', 'People or animals that live in a place.', 'habitare', 'Latin', 'Year 5', '-ant + -s', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('innocuous', 'Harmless; not likely to cause damage.', 'innocuus', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('insane', 'Mentally ill; very foolish.', 'insanus', 'Latin', 'Year 6', 'Prefix in-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('insert', 'To put something in.', 'inserere', 'Latin', 'Year 5', 'Prefix in-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('insolent', 'Rude and disrespectful.', 'insolens', 'Latin', 'Year 6', '-ent suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('inspire', 'To fill with desire or ideas.', 'inspirare', 'Latin', 'Year 5', 'Prefix in-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('intangible', 'Not able to be touched.', 'tangere', 'Latin', 'Year 6', 'Prefix in-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('intense', 'Very strong or extreme.', 'intensus', 'Latin', 'Year 5', '-ense ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('intention', 'A plan or aim.', 'intentio', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('interested', 'Wanting to know more.', 'interesse', 'Latin', 'Year 4', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('interfere', 'To get involved and hinder.', 'interferre', 'Latin', 'Year 5', 'Prefix inter-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('interior', 'The inside of something.', 'interior', 'Latin', 'Year 5', '-ior suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('interpret', 'To explain the meaning of.', 'interpretari', 'Latin', 'Year 5', 'Prefix inter-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('interrogate', 'To question formally.', 'interrogare', 'Latin', 'Year 6', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('interrupt', 'To stop something temporarily.', 'interrumpere', 'Latin', 'Year 5', 'Prefix inter-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('invalid', 'Not valid; a sick person.', 'invalidus', 'Latin', 'Year 6', 'Prefix in-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('isolation', 'The state of being alone.', 'isolare', 'Latin', 'Year 6', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('justice', 'Fair treatment; the law.', 'justitia', 'Latin', 'Year 5', '-ice suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('labour', 'Work; or the process of giving birth.', 'labor', 'Latin', 'Year 4', 'UK spelling -our', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lament', 'To express grief.', 'lamentum', 'Latin', 'Year 6', 'Letter string -ment', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('language', 'Words used to communicate.', 'lingua', 'Latin', 'Year 4', '-age suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('latter', 'The second of two things mentioned.', 'lætra', 'Old English', 'Year 5', 'Double t', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lavish', 'Very generous; luxurious.', 'lavasse', 'French', 'Year 6', '-ish suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lean', 'To bend or rest; thin.', 'hleonian', 'Old English', 'Year 4', 'Letter string -ean', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('leisure', 'Free time for relaxation.', 'leisir', 'French', 'Year 5', 'Letter string -sure', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lenient', 'Not strict; merciful.', 'lenire', 'Latin', 'Year 6', '-ent suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('liable', 'Responsible; likely to.', 'ligare', 'Latin', 'Year 6', '-able suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('liberal', 'Generous; open to new ideas.', 'liberalis', 'Latin', 'Year 6', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('liberty', 'Freedom.', 'libertas', 'Latin', 'Year 5', '-ty suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('library', 'A place where books are kept.', 'libraria', 'Latin', 'Year 4', '-ary suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lightning', 'A flash of electricity in the sky.', 'lighten', 'Old English', 'Year 4', '-ing suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('limb', 'An arm, leg, or branch.', 'lim', 'Old English', 'Year 5', 'Silent b', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('limit', 'A boundary; the greatest amount allowed.', 'limes', 'Latin', 'Year 4', 'Letter string -it', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('linger', 'To stay longer than necessary.', 'lengeren', 'Old English', 'Year 5', '-er suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lodge', 'A small house; to stay temporarily.', 'loge', 'French', 'Year 5', 'Letter string -dge', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('lofty', 'Very high; noble.', 'loft', 'Norse', 'Year 6', '-y suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('loneliness', 'The state of being alone and sad.', 'lonely', 'English', 'Year 5', '-ness suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('loyal', 'Faithful and devoted.', 'leal', 'French', 'Year 5', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('majestic', 'Grand and impressive.', 'majestas', 'Latin', 'Year 6', '-ic suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('malady', 'An illness.', 'maladie', 'French', 'Year 6', 'Prefix mal-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('margin', 'The edge or border.', 'margo', 'Latin', 'Year 5', '-in suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mariner', 'A sailor.', 'marinus', 'Latin', 'Year 6', '-er suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('matte', 'Dull; not shiny.', 'mat', 'French', 'Year 6', 'Double t', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('maximum', 'The greatest amount.', 'maximum', 'Latin', 'Year 5', '-um ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('meagre', 'Small in amount.', 'macre', 'French', 'Year 6', 'UK spelling -re', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('meant', 'Past of mean; intended.', 'mean', 'Old English', 'Year 4', 'Letter string -eant', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('merchant', 'A person who sells goods.', 'mercari', 'Latin', 'Year 5', '-ant suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mercy', 'Compassion; forgiveness.', 'merces', 'Latin', 'Year 5', 'Letter string -cy', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mere', 'Only; nothing more than.', 'merus', 'Latin', 'Year 5', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('meticulous', 'Very careful about details.', 'meticulosus', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('minimum', 'The smallest amount.', 'minimum', 'Latin', 'Year 5', '-um ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('moderate', 'Not extreme; average.', 'moderatus', 'Latin', 'Year 5', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('modest', 'Not boastful; small.', 'modestus', 'Latin', 'Year 5', '-est suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('moral', 'Relating to right and wrong.', 'moralis', 'Latin', 'Year 5', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mortal', 'Subject to death; deadly.', 'mortalis', 'Latin', 'Year 6', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mysterious', 'Hard to understand; full of mystery.', 'mysterium', 'Latin', 'Year 5', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('nauseous', 'Feeling sick.', 'nausea', 'Greek', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('neat', 'Tidy; clever.', 'nitidus', 'Latin', 'Year 4', 'Letter string -eat', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('necessary', 'Required; needed.', 'necessarius', 'Latin', 'Year 5', '-ary suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('nimble', 'Quick and light in movement.', 'næmel', 'Old English', 'Year 5', 'Letter string -ble', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('no one', 'Nobody; not any person.', 'no + one', 'English', 'Year 4', 'Two-word phrase', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('noted', 'Famous; well-known.', 'notare', 'Latin', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('nuisance', 'Something annoying.', 'nuire', 'French', 'Year 5', '-ance suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('nurseryman', 'A person who grows plants for sale.', 'nursery + man', 'English', 'Year 6', 'Compound word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('oath', 'A solemn promise.', 'ath', 'Old English', 'Year 5', 'Letter string -oath', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('object', 'A thing; to disagree.', 'obicere', 'Latin', 'Year 4', 'Prefix ob-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('objection', 'An expression of disagreement.', 'objectio', 'Latin', 'Year 5', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('oblige', 'To require; to do a favour.', 'obligare', 'Latin', 'Year 6', 'Prefix ob-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('obscure', 'Not well known; dark.', 'obscurus', 'Latin', 'Year 6', 'Letter string -ure', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('obstinate', 'Stubborn; refusing to change.', 'obstinatus', 'Latin', 'Year 6', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('occupy', 'To fill or take up space.', 'occupare', 'Latin', 'Year 5', 'Prefix oc-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('occur', 'To happen.', 'occurrere', 'Latin', 'Year 5', 'Double c', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('odour', 'A smell.', 'odor', 'Latin', 'Year 5', 'UK spelling -our', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('offend', 'To upset or insult.', 'offendere', 'Latin', 'Year 5', 'Prefix of-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('omen', 'A sign of something to come.', 'omen', 'Latin', 'Year 6', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('opportunity', 'A chance to do something.', 'opportunitas', 'Latin', 'Year 5', '-ity suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('oppose', 'To be against.', 'opponere', 'Latin', 'Year 5', 'Prefix op-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('oppress', 'To treat cruelly or unfairly.', 'opprimere', 'Latin', 'Year 6', 'Prefix op-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('option', 'A choice.', 'optio', 'Latin', 'Year 5', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ordeal', 'A difficult or painful experience.', 'ordal', 'Old English', 'Year 6', 'Letter string -eal', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('origin', 'The point where something begins.', 'origo', 'Latin', 'Year 5', '-in suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('orthodontist', 'A dentist who straightens teeth.', 'ortho + odont', 'Greek', 'Year 6', '-ist suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ostentatious', 'Showy; trying to impress.', 'ostentare', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('paid', 'Past of pay; given money.', 'pay', 'Latin', 'Year 4', 'Letter string -aid', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('painstaking', 'Very careful and thorough.', 'pains + taking', 'English', 'Year 6', 'Compound word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('palaeontologist', 'A scientist who studies fossils and dinosaurs.', 'palaios + ont', 'Greek', 'Year 6', '-ist suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('parallel', 'Side by side and never meeting.', 'parallelos', 'Greek', 'Year 5', 'Double l', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('Parliament', 'The law-making body of a country.', 'parlement', 'French', 'Year 5', 'Proper noun', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('passive', 'Not active; accepting without resistance.', 'passivus', 'Latin', 'Year 6', '-ive suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pasture', 'Land where animals graze.', 'pastura', 'Latin', 'Year 5', '-ure suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('peak', 'The pointed top; the highest point.', 'pec', 'Unknown', 'Year 4', 'Letter string -eak', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('peculiar', 'Strange; unusual.', 'peculiaris', 'Latin', 'Year 5', '-ar suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('perceive', 'To become aware of.', 'percipere', 'Latin', 'Year 6', 'Prefix per-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('peril', 'Danger.', 'periculum', 'Latin', 'Year 6', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('perilous', 'Full of danger.', 'periculosus', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('perish', 'To die or be destroyed.', 'perir', 'French', 'Year 6', '-ish suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('permit', 'To allow; a document allowing something.', 'permittere', 'Latin', 'Year 5', 'Prefix per-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('perplexed', 'Confused and puzzled.', 'perplexus', 'Latin', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('persuade', 'To convince someone.', 'persuadere', 'Latin', 'Year 5', 'Prefix per-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('physical', 'Relating to the body or matter.', 'physicus', 'Greek', 'Year 5', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('physiotherapy', 'Treatment using exercise and movement.', 'physio + therapy', 'Greek', 'Year 6', 'Compound word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pigment', 'A substance that gives colour.', 'pigmentum', 'Latin', 'Year 6', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pioneer', 'A person who goes first.', 'pionnier', 'French', 'Year 5', '-eer suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('placid', 'Calm and peaceful.', 'placidus', 'Latin', 'Year 6', 'Letter string -id', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pledge', 'A solemn promise.', 'plege', 'Old French', 'Year 5', 'Letter string -dge', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('plume', 'A feather; a feathery shape.', 'pluma', 'Latin', 'Year 6', 'Letter string -ume', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('plunder', 'To steal by force.', 'plundrian', 'German', 'Year 6', '-er suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('plunge', 'To dive or fall suddenly.', 'plongier', 'French', 'Year 5', 'Letter string -unge', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('polarity', 'The state of having two opposite poles.', 'polaris', 'Latin', 'Year 6', '-ity suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pompous', 'Acting self-important.', 'pompa', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('poultry', 'Birds kept for eggs or meat.', 'poulet', 'French', 'Year 5', 'Letter string -try', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('precarious', 'Unstable; risky.', 'precarius', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('prejudice', 'Unfair dislike based on group.', 'praejudicium', 'Latin', 'Year 6', 'Prefix pre-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('present', 'Here now; a gift; to give.', 'praesens', 'Latin', 'Year 4', 'Prefix pre-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('privilege', 'A special right or advantage.', 'privilegium', 'Latin', 'Year 6', '-ege ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('probably', 'Almost certainly.', 'probabilis', 'Latin', 'Year 4', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('proclaim', 'To announce publicly.', 'proclamare', 'Latin', 'Year 6', 'Prefix pro-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('procure', 'To obtain.', 'procurare', 'Latin', 'Year 6', 'Prefix pro-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('profession', 'A paid occupation.', 'professio', 'Latin', 'Year 5', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('profit', 'Financial gain; benefit.', 'profit', 'Latin', 'Year 5', 'Letter string -it', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('programme', 'A plan; a broadcast.', 'programma', 'Greek', 'Year 4', 'UK spelling -mme', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('prohibit', 'To forbid.', 'prohibere', 'Latin', 'Year 6', 'Prefix pro-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('prominent', 'Important; sticking out.', 'prominens', 'Latin', 'Year 6', '-ent suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('promote', 'To advance; to advertise.', 'promovere', 'Latin', 'Year 5', 'Prefix pro-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('prompt', 'Quick; on time; to cause.', 'promptus', 'Latin', 'Year 5', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('pronunciation', 'The way a word is said.', 'pronuntiatio', 'Latin', 'Year 6', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('proportion', 'A part of a whole; balance.', 'proportio', 'Latin', 'Year 5', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('prosperous', 'Successful; wealthy.', 'prosper', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('provoke', 'To cause a reaction.', 'provocare', 'Latin', 'Year 6', 'Prefix pro-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('public', 'Open to everyone.', 'publicus', 'Latin', 'Year 4', '-ic suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('punctual', 'On time.', 'punctualis', 'Latin', 'Year 6', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('puncture', 'A small hole; to make a hole.', 'punctura', 'Latin', 'Year 6', '-ure suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('purpose', 'The reason for something.', 'purposer', 'French', 'Year 4', '-pose ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('quaint', 'Old-fashioned and charming.', 'coint', 'French', 'Year 6', 'Letter string -aint', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('queer', 'Strange; odd.', 'quer', 'German', 'Year 5', 'Letter string -eer', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('quell', 'To put an end to.', 'cwellan', 'Old English', 'Year 6', 'Letter string -ell', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('quench', 'To satisfy thirst; to put out.', 'cwencan', 'Old English', 'Year 6', 'Letter string -ench', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('queue', 'A line of people waiting.', 'queue', 'French', 'Year 5', 'Letter string -ueue', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('quiet', 'Making little or no sound.', 'quietus', 'Latin', 'Year 4', 'Letter string -iet', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('quite', 'Completely; to a degree.', 'quit', 'Latin', 'Year 4', 'Letter string -ite', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('quiver', 'To tremble; a case for arrows.', 'cwifer', 'Old English', 'Year 5', '-er suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('raiment', 'Clothing.', 'array + ment', 'French', 'Year 6', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ramble', 'To walk for pleasure; to talk aimlessly.', 'romen', 'Middle Dutch', 'Year 5', 'Letter string -ble', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rank', 'A position; a row; foul-smelling.', 'ranc', 'French', 'Year 5', 'Letter string -ank', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rare', 'Uncommon; not fully cooked.', 'rarus', 'Latin', 'Year 4', 'Letter string -are', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('really', 'In fact; very.', 'real', 'Latin', 'Year 4', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('receive', 'To get or be given.', 'recipere', 'Latin', 'Year 4', 'i before e', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('recite', 'To say aloud from memory.', 'recitare', 'Latin', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('refuse', 'To say no; waste.', 'refusare', 'Latin', 'Year 4', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('release', 'To set free; to let go.', 'relaxare', 'Latin', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('repent', 'To feel sorry for wrongdoing.', 'repentir', 'French', 'Year 6', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('reprimand', 'A formal rebuke.', 'réprimande', 'French', 'Year 6', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('reserve', 'To keep for later; a supply.', 'reservare', 'Latin', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('reside', 'To live in a place.', 'residere', 'Latin', 'Year 6', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('residence', 'A person''s home.', 'residentia', 'Latin', 'Year 5', '-ence suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('resign', 'To give up a job; to accept.', 'resignare', 'Latin', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('resolve', 'To decide; to fix a problem.', 'resolvere', 'Latin', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('resort', 'To turn to; a place for holiday.', 'resortir', 'French', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('restaurant', 'A place where meals are served.', 'restaurer', 'French', 'Year 5', '-ant suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('restore', 'To bring back to original state.', 'restaurare', 'Latin', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('restrain', 'To hold back.', 'restreindre', 'French', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('retain', 'To keep possession of.', 'retinere', 'Latin', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('retreat', 'To move back; a quiet place.', 'retraiter', 'French', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('reveal', 'To make known.', 'revelare', 'Latin', 'Year 5', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('revive', 'To bring back to life or use.', 'revivere', 'Latin', 'Year 6', 'Prefix re-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rhyme', 'Words with the same ending sound.', 'ryme', 'Old French', 'Year 4', 'Silent h', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ridiculous', 'Silly; deserving mockery.', 'ridiculosus', 'Latin', 'Year 5', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rigid', 'Stiff; not flexible.', 'rigidus', 'Latin', 'Year 6', 'Letter string -id', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('roam', 'To wander.', 'ramen', 'Old English', 'Year 5', 'Letter string -oam', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('robust', 'Strong and healthy.', 'robustus', 'Latin', 'Year 6', 'Letter string -ust', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rogue', 'A dishonest person; mischievous.', 'rogue', 'Unknown', 'Year 6', 'Letter string -ogue', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rowdy', 'Noisy and disorderly.', 'rowdy', 'Unknown', 'Year 6', '-y suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('rural', 'Relating to the countryside.', 'ruralis', 'Latin', 'Year 5', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sacred', 'Connected with religion; holy.', 'sacer', 'Latin', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sacrifice', 'To give up something valued.', 'sacrificium', 'Latin', 'Year 5', '-ice suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sane', 'Having a healthy mind.', 'sanus', 'Latin', 'Year 6', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sanitary', 'Clean and free from germs.', 'sanitas', 'Latin', 'Year 6', '-ary suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('satin', 'A shiny, smooth fabric.', 'zaytuni', 'Arabic', 'Year 6', 'Letter string -in', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('scanty', 'Too small in amount.', 'scant', 'Norse', 'Year 6', '-y suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('score', 'Points; twenty; to gain points.', 'skor', 'Norse', 'Year 4', 'Letter string -ore', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('scripture', 'Sacred writings.', 'scriptura', 'Latin', 'Year 6', '-ure suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('secure', 'Safe; to fix firmly.', 'securus', 'Latin', 'Year 5', 'Letter string -ure', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('seize', 'To take hold of suddenly.', 'saisir', 'French', 'Year 5', 'i before e exception', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('seldom', 'Rarely; not often.', 'seldan', 'Old English', 'Year 5', '-dom suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('separate', 'To divide; not together.', 'separare', 'Latin', 'Year 5', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sermon', 'A religious talk.', 'sermo', 'Latin', 'Year 6', 'Letter string -mon', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('shoulder', 'The joint between arm and body.', 'sculdor', 'Old English', 'Year 4', '-er suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('shrine', 'A holy place.', 'scrinium', 'Latin', 'Year 5', 'Letter string -ine', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('shrink', 'To become smaller.', 'scrincan', 'Old English', 'Year 5', 'Letter string -ink', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('signature', 'A person''s name written by hand.', 'signatura', 'Latin', 'Year 5', '-ure suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sincere', 'Genuine; honest.', 'sincerus', 'Latin', 'Year 5', 'Letter string -ere', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sincerely', 'In a genuine way.', 'sincere', 'Latin', 'Year 5', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sleek', 'Smooth and glossy.', 'slic', 'Old English', 'Year 5', 'Letter string -eek', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('slope', 'A surface that goes up or down.', 'aslopen', 'Middle English', 'Year 5', 'Letter string -ope', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sly', 'Cunning; secretive.', 'sleigh', 'Old Norse', 'Year 5', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sober', 'Not drunk; serious.', 'sobrius', 'Latin', 'Year 6', 'Letter string -ober', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('soldier', 'A member of an army.', 'soldier', 'French', 'Year 4', '-er suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sow', 'To plant seeds; a female pig.', 'sawan', 'Old English', 'Year 5', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('special', 'Different from usual; important.', 'specialis', 'Latin', 'Year 4', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stern', 'Strict; the back of a ship.', 'styrne', 'Old English', 'Year 5', 'Letter string -ern', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stomach', 'The organ that digests food.', 'stomachus', 'Greek', 'Year 4', 'Letter string -ach', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stoop', 'To bend forward; a small porch.', 'stoupen', 'Dutch', 'Year 5', 'Letter string -oop', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stout', 'Sturdy; rather fat.', 'stout', 'French', 'Year 5', 'Letter string -out', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stress', 'Pressure; emphasis.', 'stressus', 'Latin', 'Year 5', 'Double s', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stretched', 'Extended to full length.', 'streccan', 'Old English', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stubborn', 'Refusing to change.', 'stuborn', 'Unknown', 'Year 5', '-orn ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sturdy', 'Strong and solid.', 'esturdi', 'French', 'Year 5', '-y suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('subdued', 'Quiet and controlled.', 'subduere', 'Latin', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('submissive', 'Obedient; yielding.', 'submissus', 'Latin', 'Year 6', '-ive suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('submit', 'To yield; to present for consideration.', 'submittere', 'Latin', 'Year 5', 'Prefix sub-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('subterfuge', 'A sneaky trick to hide the truth.', 'subterfugium', 'Latin', 'Year 6', 'Prefix sub-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('subterranean', 'Under the ground.', 'sub + terra', 'Latin', 'Year 6', 'Prefix sub-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('subtropical', 'Relating to regions near the tropics.', 'sub + tropical', 'Latin', 'Year 6', 'Prefix sub-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('successful', 'Achieving success.', 'success', 'Latin', 'Year 5', '-ful suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('succumb', 'To give in to pressure.', 'succumbere', 'Latin', 'Year 6', 'Prefix suc-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sufficient', 'Enough.', 'sufficiens', 'Latin', 'Year 5', '-ent suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('suggest', 'To put forward an idea.', 'suggerere', 'Latin', 'Year 5', 'Prefix sug-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('summit', 'The highest point.', 'summitas', 'Latin', 'Year 5', 'Double m', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('superfluous', 'More than needed.', 'superfluus', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('superior', 'Better; higher in rank.', 'superior', 'Latin', 'Year 5', '-ior suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('supposed', 'Generally believed; required.', 'supposer', 'French', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('surprise', 'An unexpected event.', 'surprendre', 'French', 'Year 4', 'Prefix sur-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('suspect', 'To believe someone may be guilty.', 'suspicere', 'Latin', 'Year 5', 'Prefix sus-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('suspend', 'To hang; to stop temporarily.', 'suspendere', 'Latin', 'Year 5', 'Prefix sus-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('symbol', 'Something that represents something else.', 'symbolum', 'Greek', 'Year 5', 'Letter string -bol', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('system', 'A set of parts working together.', 'systema', 'Greek', 'Year 5', 'Letter string -tem', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('temperate', 'Mild; not extreme.', 'temperatus', 'Latin', 'Year 6', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tempestuous', 'Stormy; full of strong emotion.', 'tempestas', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('temptation', 'The desire to do something wrong.', 'temptatio', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('they', 'Those people or things.', 'thai', 'Old Norse', 'Year 3', 'Letter string -ey', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('thrust', 'To push suddenly and hard.', 'thrysta', 'Old Norse', 'Year 5', 'Letter string -ust', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tomorrow', 'The day after today.', 'to + morrow', 'Old English', 'Year 4', 'Compound word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('torment', 'Severe suffering.', 'tormentum', 'Latin', 'Year 6', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('traitor', 'A person who betrays.', 'traitre', 'French', 'Year 6', '-or suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tranquil', 'Calm and peaceful.', 'tranquillus', 'Latin', 'Year 6', 'Letter string -quil', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tries', 'Attempts; third person of try.', 'try', 'French', 'Year 4', '-ies ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('trifle', 'A small amount; a dessert.', 'trufle', 'French', 'Year 6', 'Letter string -fle', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('trivia', 'Unimportant details.', 'trivium', 'Latin', 'Year 6', 'Letter string -ia', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('trivial', 'Unimportant.', 'trivialis', 'Latin', 'Year 6', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('turbulent', 'Violently disturbed.', 'turbulentus', 'Latin', 'Year 6', '-ent suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('twilight', 'The dim light after sunset.', 'twi- + light', 'Old English', 'Year 5', 'Compound word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tyrant', 'A cruel ruler.', 'tyrannus', 'Greek', 'Year 6', '-ant suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('unfathomable', 'Impossible to understand.', 'fathom', 'Old English', 'Year 6', 'Prefix un-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('uniform', 'The same throughout; clothing.', 'uniformis', 'Latin', 'Year 5', 'Prefix uni-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('union', 'A joining together.', 'unio', 'Latin', 'Year 5', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('unite', 'To join together.', 'unire', 'Latin', 'Year 5', 'Prefix un-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('unnecessary', 'Not needed.', 'necessary', 'Latin', 'Year 5', 'Prefix un-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('unorthodox', 'Not conventional.', 'orthodox', 'Greek', 'Year 6', 'Prefix un-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('unsurpassed', 'Not exceeded; best.', 'surpass', 'French', 'Year 6', 'Prefix un-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('until', 'Up to the time of.', 'til', 'Old Norse', 'Year 4', 'Letter string -til', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('vacant', 'Empty; not occupied.', 'vacare', 'Latin', 'Year 5', '-ant suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('vanished', 'Disappeared completely.', 'vanir', 'French', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('vapour', 'Moisture in the air; steam.', 'vapor', 'Latin', 'Year 5', 'UK spelling -our', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('vast', 'Very large.', 'vastus', 'Latin', 'Year 5', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('vehicle', 'A thing used for transport.', 'vehiculum', 'Latin', 'Year 5', '-cle suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('veil', 'A piece of cloth that hides the face.', 'velum', 'Latin', 'Year 5', 'Letter string -eil', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('venerable', 'Worthy of respect due to age.', 'venerabilis', 'Latin', 'Year 6', '-able suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ventilation', 'The movement of fresh air.', 'ventilare', 'Latin', 'Year 6', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('vessel', 'A ship; a container.', 'vascellum', 'Latin', 'Year 5', 'Double s', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('vicarious', 'Experienced through someone else.', 'vicarius', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('virtuous', 'Having good moral character.', 'virtuosus', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('volatile', 'Changing quickly; explosive.', 'volatilis', 'Latin', 'Year 6', '-ile suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wasteful', 'Using more than needed.', 'waste', 'Latin', 'Year 5', '-ful suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('weary', 'Very tired.', 'werig', 'Old English', 'Year 5', 'Letter string -eary', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('weird', 'Strange; uncanny.', 'wyrd', 'Old English', 'Year 5', 'i before e exception', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wholesome', 'Good for health or morals.', 'hal', 'Old English', 'Year 5', '-some suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wholly', 'Completely; entirely.', 'whole', 'Old English', 'Year 5', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wither', 'To dry up and shrink.', 'witheren', 'Old English', 'Year 5', '-er suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('worthy', 'Deserving of something.', 'weorth', 'Old English', 'Year 5', '-y suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wound', 'An injury; to injure.', 'wund', 'Old English', 'Year 4', 'Letter string -ound', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('wretched', 'Very unhappy; of poor quality.', 'wrecched', 'Old English', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('yield', 'To produce; to give way.', 'gieldan', 'Old English', 'Year 5', 'Letter string -ield', '{}', '{}', 'Example sentence to be updated by teacher.', '{}')
ON CONFLICT (word) DO NOTHING;
