-- Seed word bank with words from Page 2 of the word list (no duplicates).
-- Run this in Supabase SQL Editor. Uses ON CONFLICT to skip words that already exist.

INSERT INTO vocab_words (word, definition, root, origin, year_group, learning_point, synonyms, antonyms, example, letter_strings)
VALUES
  ('caution', 'Care to avoid danger or risk.', 'cautio', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cease', 'To stop.', 'cesser', 'Latin', 'Year 5', 'Letter string -ease', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cemetery', 'A place where dead people are buried.', 'koimeterion', 'Greek', 'Year 5', 'Letter string -ery', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('chaos', 'Complete disorder and confusion.', 'khaos', 'Greek', 'Year 5', 'Greek origin', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('charred', 'Burned to charcoal; scorched.', 'char', 'Unknown', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('choreographer', 'A person who designs dances.', 'choros + graph', 'Greek', 'Year 6', '-er suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('clemency', 'Mercy or leniency.', 'clementia', 'Latin', 'Year 6', '-cy suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('coarse', 'Rough; not fine.', 'cors', 'Latin', 'Year 5', 'Letter string -arse', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('coax', 'To persuade gently.', 'cokes', 'Unknown', 'Year 5', 'Letter string -oax', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('college', 'A place of higher education.', 'collegium', 'Latin', 'Year 4', '-lege ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('colour', 'The appearance of things from light.', 'color', 'Latin', 'Year 3', 'UK spelling -our', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('combination', 'A mix or joining of things.', 'combinare', 'Latin', 'Year 5', '-ation suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('commence', 'To begin.', 'commencer', 'French', 'Year 5', 'Prefix com-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('commit', 'To do something; to pledge.', 'committere', 'Latin', 'Year 5', 'Prefix com-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('communicate', 'To share information.', 'communicare', 'Latin', 'Year 5', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('community', 'A group of people living together.', 'communitas', 'Latin', 'Year 4', '-ity suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('companion', 'A person who accompanies another.', 'companio', 'Latin', 'Year 5', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('company', 'A business; or companionship.', 'companion', 'Latin', 'Year 4', 'Letter string -any', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('compel', 'To force someone to do something.', 'compellere', 'Latin', 'Year 6', 'Prefix com-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('competition', 'An event to see who is best.', 'competere', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('completely', 'Totally; in every way.', 'complete', 'Latin', 'Year 4', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('complex', 'Complicated; made of many parts.', 'complexus', 'Latin', 'Year 5', 'Letter string -ex', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('composition', 'Something made by combining parts; a piece of writing.', 'componere', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('comprehend', 'To understand fully.', 'comprehendere', 'Latin', 'Year 6', 'Prefix com-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('contribute', 'To give something towards a cause.', 'contribuere', 'Latin', 'Year 5', '-ute suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('comrade', 'A friend or companion, especially in difficult times.', 'camarade', 'Spanish', 'Year 6', '-ade suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conceal', 'To hide or keep secret.', 'concelare', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conceited', 'Having too high an opinion of oneself.', 'conceit', 'Latin', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('concentrated', 'Focused; undiluted.', 'concentrare', 'Latin', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conclude', 'To bring or come to an end.', 'concludere', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conclusion', 'The end or result.', 'conclusio', 'Latin', 'Year 5', '-ion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('condemn', 'To express strong disapproval.', 'condemnare', 'Latin', 'Year 6', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conferred', 'Granted or discussed.', 'conferre', 'Latin', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('confine', 'To restrict or keep within limits.', 'confinis', 'Latin', 'Year 6', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conscience', 'A moral sense of right and wrong.', 'conscientia', 'Latin', 'Year 5', '-ence suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conscious', 'Aware; awake.', 'conscius', 'Latin', 'Year 5', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('consent', 'Permission or agreement.', 'consentire', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conserve', 'To protect from loss or harm.', 'conservare', 'Latin', 'Year 5', '-erve ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('consideration', 'Careful thought; thoughtfulness.', 'considerare', 'Latin', 'Year 5', '-ation suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('consist', 'To be made of.', 'consistere', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conspire', 'To plan secretly together.', 'conspirare', 'Latin', 'Year 6', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('constant', 'Continuous; unchanging.', 'constans', 'Latin', 'Year 5', '-ant suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('consume', 'To use up; to eat or drink.', 'consumere', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('contemporary', 'Living or occurring at the same time.', 'tempus', 'Latin', 'Year 6', '-ary suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('contempt', 'Strong dislike or scorn.', 'contemptus', 'Latin', 'Year 6', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('content', 'Satisfied; or what is contained.', 'contentus', 'Latin', 'Year 4', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('contest', 'A competition; to dispute.', 'contestari', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('contract', 'A formal agreement; to shrink.', 'contractus', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('contrast', 'A striking difference.', 'contrastare', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('conventional', 'Following tradition; usual.', 'convention', 'Latin', 'Year 6', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('convert', 'To change in form or purpose.', 'convertere', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('convey', 'To transport or communicate.', 'conviare', 'Latin', 'Year 5', 'Letter string -ey', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('convict', 'To declare guilty; a prisoner.', 'convictus', 'Latin', 'Year 6', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('convince', 'To persuade by argument.', 'convincere', 'Latin', 'Year 5', 'Prefix con-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('correct', 'Right; to fix errors.', 'correctus', 'Latin', 'Year 4', 'Prefix cor-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('covert', 'Secret or hidden.', 'cooperire', 'Latin', 'Year 6', 'Letter string -vert', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('covet', 'To desire something belonging to another.', 'cupere', 'Latin', 'Year 6', 'Letter string -et', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('coy', 'Pretending shyness.', 'coi', 'French', 'Year 6', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('credit', 'Belief in reliability; money available.', 'credere', 'Latin', 'Year 4', 'Letter string -it', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cultivate', 'To prepare land; to develop.', 'cultivare', 'Latin', 'Year 6', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cunning', 'Clever at deceiving.', 'cunnen', 'Old English', 'Year 5', '-ing suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('curb', 'To restrain; a restraint or edge.', 'courbe', 'French', 'Year 5', 'Letter string -urb', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('curious', 'Eager to know; strange.', 'curiosus', 'Latin', 'Year 4', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('curt', 'Brief to the point of rudeness.', 'curtus', 'Latin', 'Year 6', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('custom', 'A tradition; made to order.', 'consuetudo', 'Latin', 'Year 4', '-um ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('debate', 'A formal discussion; to argue.', 'debattre', 'French', 'Year 5', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('debrief', 'To question after a mission.', 'brief', 'English', 'Year 6', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('deceit', 'Dishonest behaviour.', 'decipere', 'Latin', 'Year 6', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('deceive', 'To make someone believe what is not true.', 'decipere', 'Latin', 'Year 5', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('declare', 'To state formally.', 'declarare', 'Latin', 'Year 5', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('decline', 'To refuse; to decrease.', 'declinare', 'Latin', 'Year 5', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('definite', 'Certain; clearly stated.', 'definire', 'Latin', 'Year 5', '-ite suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('deliberate', 'Done on purpose; to consider carefully.', 'deliberare', 'Latin', 'Year 6', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('demolished', 'Pulled or knocked down completely.', 'demoliri', 'Latin', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('deny', 'To refuse to admit or allow.', 'denegare', 'Latin', 'Year 5', 'Letter string -eny', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('deposit', 'To put down; money in a bank.', 'deponere', 'Latin', 'Year 5', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('depot', 'A storehouse or station.', 'depot', 'French', 'Year 6', 'Silent t', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('derelict', 'Abandoned and in bad condition.', 'derelictus', 'Latin', 'Year 6', 'Latin root', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('description', 'A spoken or written account.', 'descriptio', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('despair', 'Complete loss of hope.', 'desperare', 'Latin', 'Year 6', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('desperately', 'In a desperate way.', 'desperatus', 'Latin', 'Year 5', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('despise', 'To feel strong dislike.', 'despicere', 'Latin', 'Year 6', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('destitute', 'Without basic necessities.', 'destituere', 'Latin', 'Year 6', '-ute suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('determine', 'To decide or establish.', 'determinare', 'Latin', 'Year 5', '-ine suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('develop', 'To grow or make progress.', 'developer', 'French', 'Year 5', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('device', 'A tool or machine.', 'divisus', 'Latin', 'Year 5', 'Letter string -ice', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('devote', 'To give time or effort to.', 'devovere', 'Latin', 'Year 5', 'Prefix de-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dictionary', 'A book listing words and meanings.', 'dictionarium', 'Latin', 'Year 4', '-ary suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('digest', 'To break down food; a summary.', 'digestus', 'Latin', 'Year 6', 'Prefix di-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dilapidated', 'In a state of disrepair.', 'dilapidare', 'Latin', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('diluted', 'Weakened by adding water.', 'dilutus', 'Latin', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('din', 'A loud, continuous noise.', 'dyne', 'Old English', 'Year 5', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('disappear', 'To vanish from sight.', 'dis- + appear', 'Latin', 'Year 4', 'Prefix dis-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('disappointed', 'Sad because expectations were not met.', 'dis- + appoint', 'Latin', 'Year 4', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('disarray', 'A state of disorder.', 'dis- + array', 'French', 'Year 6', 'Prefix dis-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('disastrous', 'Causing great damage.', 'disastro', 'Italian', 'Year 5', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('disclose', 'To reveal or make known.', 'disclaudere', 'Latin', 'Year 6', 'Prefix dis-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('discontent', 'Dissatisfaction.', 'dis- + content', 'Latin', 'Year 6', 'Prefix dis-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dishevelled', 'Untidy; disordered.', 'dischevele', 'French', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dismal', 'Depressing; gloomy.', 'dies malus', 'Latin', 'Year 6', 'Prefix dis-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('disperse', 'To spread over a wide area.', 'dispergere', 'Latin', 'Year 6', 'Prefix dis-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dispute', 'A disagreement; to argue.', 'disputare', 'Latin', 'Year 5', 'Prefix dis-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('distasteful', 'Unpleasant; offensive.', 'dis- + taste', 'English', 'Year 6', '-ful suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('distinct', 'Clearly different.', 'distinctus', 'Latin', 'Year 5', 'Prefix dis-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('distinguished', 'Successful and respected.', 'distinguere', 'Latin', 'Year 6', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('distress', 'Extreme anxiety or pain.', 'distresser', 'French', 'Year 5', 'Prefix dis-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('divine', 'Of or like a god.', 'divinus', 'Latin', 'Year 6', '-ine suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('divinity', 'The state of being divine.', 'divinitas', 'Latin', 'Year 6', '-ity suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('domestic', 'Relating to the home or country.', 'domesticus', 'Latin', 'Year 5', '-ic suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dose', 'A measured amount of medicine.', 'dosis', 'Greek', 'Year 5', 'Letter string -ose', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('drought', 'A long period without rain.', 'drugath', 'Old English', 'Year 5', 'Letter string -ough', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dumb', 'Unable to speak; stupid.', 'dumb', 'Old English', 'Year 4', 'Silent b', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('dwelling', 'A place where someone lives.', 'dwell', 'Old English', 'Year 5', '-ing suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('earnest', 'Serious and sincere.', 'eornost', 'Old English', 'Year 6', 'Letter string -ear', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('economical', 'Using resources carefully.', 'oikonomia', 'Greek', 'Year 5', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('elect', 'To choose by vote.', 'electus', 'Latin', 'Year 5', 'Prefix e-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('elude', 'To escape or avoid.', 'eludere', 'Latin', 'Year 6', 'Prefix e-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('embarrass', 'To cause to feel awkward.', 'embarrasser', 'French', 'Year 5', 'Double r, double s', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('embrace', 'To hold closely; to accept.', 'embracer', 'French', 'Year 5', 'Prefix em-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('emerge', 'To come out into view.', 'emergere', 'Latin', 'Year 5', 'Prefix e-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('empire', 'A group of countries under one rule.', 'imperium', 'Latin', 'Year 5', 'Letter string -ire', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('employ', 'To give work to.', 'implicare', 'Latin', 'Year 4', 'Prefix em-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('endeavour', 'To try hard; an effort.', 'put in dever', 'French', 'Year 5', 'UK spelling -our', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('endure', 'To suffer patiently; to last.', 'indurare', 'Latin', 'Year 5', 'Prefix en-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('enterprise', 'A project or business.', 'enterprise', 'French', 'Year 5', 'Letter string -ise', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('entire', 'Whole; complete.', 'integer', 'Latin', 'Year 4', 'Letter string -ire', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('entirely', 'Completely.', 'entire', 'Latin', 'Year 4', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('environment', 'Surroundings; natural world.', 'environ', 'French', 'Year 5', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('equip', 'To supply with what is needed.', 'eschiper', 'French', 'Year 5', 'Letter string -quip', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('equipment', 'Tools or gear needed.', 'equip', 'French', 'Year 5', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('equipped', 'Provided with what is needed.', 'equiper', 'French', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('erect', 'Upright; to build.', 'erigere', 'Latin', 'Year 6', 'Prefix e-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('errand', 'A short trip to do a task.', 'aerend', 'Old English', 'Year 5', 'Double r', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('especially', 'Particularly; mainly.', 'special', 'Latin', 'Year 4', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('estimate', 'A rough calculation; to guess.', 'aestimare', 'Latin', 'Year 5', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('evaluation', 'Assessment of value or quality.', 'evaluare', 'Latin', 'Year 6', '-ation suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('evident', 'Clear; obvious.', 'evidens', 'Latin', 'Year 5', '-ent suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('exaggerate', 'To represent as larger than truth.', 'exaggerare', 'Latin', 'Year 5', '-ate suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('excellent', 'Very good indeed.', 'excellere', 'Latin', 'Year 4', '-ent suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('excitement', 'A feeling of enthusiasm.', 'excite', 'Latin', 'Year 4', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('exciting', 'Causing excitement.', 'excite', 'Latin', 'Year 4', '-ing suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('exclaim', 'To cry out suddenly.', 'exclamare', 'Latin', 'Year 5', 'Prefix ex-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('existence', 'The state of existing.', 'existere', 'Latin', 'Year 5', '-ence suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('expel', 'To force to leave.', 'expellere', 'Latin', 'Year 6', 'Prefix ex-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('expense', 'The cost of something.', 'expensa', 'Latin', 'Year 5', '-ense ending', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('explanation', 'A statement that makes something clear.', 'explanare', 'Latin', 'Year 5', '-ation suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('extended', 'Stretched out; prolonged.', 'extendere', 'Latin', 'Year 5', '-ed suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('exterior', 'Outer surface or part.', 'exterior', 'Latin', 'Year 6', '-ior suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('extinction', 'The state of being extinct.', 'extinctio', 'Latin', 'Year 6', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('extract', 'To remove or take out.', 'extrahere', 'Latin', 'Year 5', 'Prefix ex-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('extremely', 'To a very great degree.', 'extreme', 'Latin', 'Year 4', '-ly suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('famine', 'Extreme shortage of food.', 'famin', 'Latin', 'Year 6', '-ine suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fatal', 'Causing death.', 'fatalis', 'Latin', 'Year 6', '-al suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fatigue', 'Extreme tiredness.', 'fatigue', 'French', 'Year 6', 'Letter string -gue', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('favourite', 'Preferred above others.', 'favoritus', 'Latin', 'Year 4', 'UK spelling -our', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('feeble', 'Weak; lacking strength.', 'fleble', 'Latin', 'Year 5', 'Letter string -ee', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('feign', 'To pretend.', 'feindre', 'French', 'Year 6', 'Letter string -eign', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fertile', 'Producing abundant growth.', 'fertilis', 'Latin', 'Year 6', '-ile suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('flamboyant', 'Showy and confident.', 'flamboyer', 'French', 'Year 6', '-ant suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('flawless', 'Without any flaws.', 'flaw', 'Norse', 'Year 5', '-less suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('flee', 'To run away.', 'fleon', 'Old English', 'Year 5', 'Letter string -ee', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fleet', 'A group of ships; fast.', 'fleotan', 'Old English', 'Year 5', 'Letter string -eet', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('flora', 'Plants of a region.', 'Flora', 'Latin', 'Year 6', 'Latin origin', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('flourish', 'To grow well; to thrive.', 'florir', 'French', 'Year 5', '-ish suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('foe', 'An enemy.', 'fah', 'Old English', 'Year 5', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('forbid', 'To order not to do.', 'forbeodan', 'Old English', 'Year 5', 'Prefix for-', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('foundation', 'The base on which something is built.', 'fundatio', 'Latin', 'Year 5', '-tion suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fragment', 'A small broken piece.', 'fragmentum', 'Latin', 'Year 5', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fragrant', 'Having a pleasant smell.', 'fragrare', 'Latin', 'Year 5', '-ant suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('frequent', 'Happening often.', 'frequens', 'Latin', 'Year 5', '-ent suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('friend', 'A person one likes.', 'freond', 'Old English', 'Year 3', 'Letter string -ied', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('frivolous', 'Not serious; silly.', 'frivolus', 'Latin', 'Year 6', '-ous suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('fund', 'Money set aside; to provide money.', 'fond', 'Latin', 'Year 5', 'Short word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('garment', 'An item of clothing.', 'garnement', 'French', 'Year 6', '-ment suffix', '{}', '{}', 'Example sentence to be updated by teacher.', '{}')
ON CONFLICT (word) DO NOTHING;
