-- Foundation / high-frequency sight words (First–Third 100). No duplicates: run in Supabase SQL Editor.
-- Uses ON CONFLICT (word) DO NOTHING so only words not already in the word bank are inserted.

INSERT INTO vocab_words (word, definition, root, origin, year_group, learning_point, synonyms, antonyms, example, letter_strings)
VALUES
  ('the', 'Used to point to a specific thing.', 'the', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('of', 'Belonging to; from.', 'of', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('and', 'Used to join words or ideas.', 'and', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('a', 'One; any.', 'an', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('to', 'In the direction of; for.', 'to', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('in', 'Inside; within.', 'in', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('is', 'Present form of be.', 'is', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('you', 'The person being spoken to.', 'you', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('that', 'Used to point out something.', 'that', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('it', 'Used for a thing already mentioned.', 'hit', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('he', 'That boy or man.', 'he', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('was', 'Past form of be.', 'was', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('for', 'Meant to be given to; because of.', 'for', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('on', 'Resting on top of.', 'on', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('are', 'Present form of be (plural).', 'are', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('as', 'In the same way; when.', 'als', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('with', 'In the company of.', 'with', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('his', 'Belonging to him.', 'his', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('they', 'Those people or things.', 'thai', 'Old Norse', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('I', 'The person speaking.', 'ic', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('at', 'In a place or time.', 'at', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('be', 'To exist; to happen.', 'beon', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('this', 'Used for something close.', 'this', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('have', 'To own or hold.', 'habban', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('from', 'Starting at; sent by.', 'from', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('or', 'Used to give a choice.', 'or', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('one', 'The number 1.', 'an', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('had', 'Past of have.', 'had', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('by', 'Next to; through; before.', 'bi', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('words', 'More than one word.', 'word', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('but', 'However; except.', 'butan', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('not', 'Used to make a negative.', 'not', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('what', 'Asking for information.', 'hwæt', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('all', 'The whole amount.', 'all', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('were', 'Past of be (plural).', 'wæron', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('we', 'The speaker and others.', 'we', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('when', 'At what time.', 'hwænne', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('your', 'Belonging to you.', 'eower', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('can', 'To be able to.', 'cunnan', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('said', 'Past of say.', 'sægde', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('there', 'In that place.', 'thær', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('use', 'To do something with.', 'us', 'Latin', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('an', 'One; any (before a vowel sound).', 'an', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('each', 'Every one.', 'ælc', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('which', 'Used to ask or point out which one.', 'hwilc', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('she', 'That girl or woman.', 'heo', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('do', 'To perform an action.', 'don', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('how', 'In what way.', 'hu', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('their', 'Belonging to them.', 'their', 'Old Norse', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('if', 'On condition that.', 'gif', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('will', 'Wish to; future tense.', 'willan', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('up', 'Towards a higher place.', 'up', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('other', 'A different one.', 'other', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('about', 'On the subject of; around.', 'abutan', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('out', 'Away from inside.', 'ut', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('many', 'A large number.', 'manig', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('then', 'At that time; next.', 'thanne', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('them', 'Those people or things (object).', 'thaim', 'Old Norse', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('these', 'These ones here.', 'these', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('so', 'In that way; therefore.', 'swa', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('some', 'An amount of.', 'sum', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('her', 'Belonging to her; her (object).', 'hire', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('would', 'Past of will; used to ask politely.', 'wolde', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('make', 'To create or do.', 'macian', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('like', 'Similar to; to enjoy.', 'lic', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('him', 'That boy or man (object).', 'him', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('into', 'To the inside of.', 'into', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('time', 'Minutes, hours, days.', 'tima', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('has', 'Present of have (he/she/it).', 'has', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('look', 'To use your eyes.', 'locian', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('two', 'The number 2.', 'twa', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('more', 'A greater amount.', 'mara', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('write', 'To form letters or words.', 'writan', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('go', 'To move from a place.', 'gan', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('see', 'To notice with your eyes.', 'seon', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('number', 'A quantity or numeral.', 'nombre', 'Latin', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('no', 'Not any; opposite of yes.', 'no', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('way', 'A path; a method.', 'weg', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('could', 'Past of can; was able to.', 'cuðe', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('people', 'Human beings.', 'peple', 'Latin', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('my', 'Belonging to me.', 'min', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('than', 'Used when comparing.', 'thanne', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('first', 'Coming before all others.', 'fyrst', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('water', 'The liquid we drink.', 'wæter', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('been', 'Past participle of be.', 'beon', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('called', 'Named; past of call.', 'call', 'Latin', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('who', 'Which person.', 'hwa', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('am', 'Present of be (I).', 'eom', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('its', 'Belonging to it.', 'hit', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('now', 'At this moment.', 'nu', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('find', 'To discover or get.', 'findan', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('long', 'Measuring a lot from end to end.', 'lang', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('down', 'Towards a lower place.', 'dun', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('day', 'A 24-hour period.', 'dæg', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('did', 'Past of do.', 'dyde', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('get', 'To obtain or become.', 'getan', 'Old Norse', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('come', 'To move towards here.', 'cuman', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('made', 'Past of make.', 'macod', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('may', 'To be allowed; might.', 'mæg', 'Old English', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('part', 'A piece of a whole.', 'part', 'Latin', 'Year 3', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('over', 'Above; across; finished.', 'ofer', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('new', 'Not old; recently made.', 'neowe', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sound', 'Something you hear; healthy.', 'sund', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('take', 'To get and hold.', 'tacan', 'Old Norse', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('only', 'Just; no more than.', 'anlic', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('little', 'Small in size or amount.', 'lytel', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('work', 'To do a job; a job.', 'weorc', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('know', 'To have in your mind.', 'cnawan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('place', 'A location.', 'place', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('years', 'More than one year.', 'gear', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('live', 'To be alive; to have a home.', 'lifian', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('me', 'The speaker (object).', 'me', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('back', 'The rear; to return.', 'bæc', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('give', 'To hand something to someone.', 'giefan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('most', 'The greatest amount.', 'mæst', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('very', 'To a high degree.', 'verai', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('after', 'Later than; behind.', 'æfter', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('things', 'Objects or ideas.', 'thing', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('our', 'Belonging to us.', 'ure', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('just', 'Only; fair; a moment ago.', 'juste', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('name', 'What someone or something is called.', 'nama', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('good', 'Of high quality; kind.', 'god', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sentence', 'A group of words that make sense.', 'sentence', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('man', 'An adult male human.', 'mann', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('think', 'To use your mind.', 'thencan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('say', 'To speak words.', 'secgan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('great', 'Very big; very good.', 'great', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('where', 'In or at what place.', 'hwær', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('help', 'To make something easier for someone.', 'helpan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('through', 'From one side to the other.', 'thurh', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('much', 'A large amount.', 'mycel', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('before', 'Earlier than; in front of.', 'beforan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('line', 'A long thin mark or queue.', 'line', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('right', 'Correct; the opposite of left.', 'riht', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('too', 'Also; more than enough.', 'to', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mean', 'To intend; unkind.', 'mænan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('old', 'Having lived a long time.', 'eald', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('any', 'One or some.', 'ænig', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('same', 'Not different.', 'same', 'Old Norse', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tell', 'To give information.', 'tellan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('boy', 'A male child.', 'boi', 'Unknown', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('follow', 'To go or come after.', 'folgian', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('came', 'Past of come.', 'com', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('want', 'To wish for.', 'vanta', 'Old Norse', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('show', 'To let someone see.', 'sceawian', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('also', 'As well; too.', 'ealswa', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('around', 'On all sides; about.', 'a round', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('farm', 'Land for growing crops or animals.', 'feorm', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('three', 'The number 3.', 'thrio', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('small', 'Little in size.', 'smæl', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('set', 'To put; a collection.', 'settan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('put', 'To place somewhere.', 'putian', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('end', 'The last part.', 'ende', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('does', 'Present of do (he/she/it).', 'do', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('another', 'One more; a different one.', 'an other', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('well', 'In a good way; healthy; a hole for water.', 'well', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('large', 'Big in size.', 'large', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('must', 'To have to.', 'moste', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('big', 'Large in size.', 'big', 'Unknown', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('even', 'Flat; still; including.', 'efen', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('such', 'Of that kind.', 'swilc', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('because', 'For the reason that.', 'by cause', 'English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('turn', 'To move around; a chance to do something.', 'turnen', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('here', 'In this place.', 'her', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('why', 'For what reason.', 'hwy', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('ask', 'To say a question.', 'ascian', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('went', 'Past of go.', 'wendan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('men', 'More than one adult male.', 'mann', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('read', 'To look at and understand words.', 'rædan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('need', 'To have to have.', 'neodian', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('land', 'The ground; a country.', 'land', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('different', 'Not the same.', 'different', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('home', 'Where you live.', 'ham', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('us', 'The speaker and others (object).', 'us', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('move', 'To change position.', 'movan', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('try', 'To attempt.', 'trier', 'French', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('kind', 'Type; caring.', 'gecynde', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hand', 'The part at the end of your arm.', 'hand', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('picture', 'A drawing or photo.', 'pictura', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('again', 'One more time.', 'ongen', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('change', 'To make or become different.', 'changer', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('off', 'Away from; not on.', 'of', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('play', 'To have fun; a drama.', 'plega', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('spell', 'To form words with letters.', 'spell', 'Old French', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('air', 'What we breathe.', 'aer', 'Greek', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('away', 'To or at a distance.', 'aweg', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('animal', 'A living creature that is not a plant.', 'animal', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('house', 'A building to live in.', 'hus', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('point', 'A dot; to show direction.', 'point', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('page', 'One side of a sheet of paper.', 'page', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('letter', 'A written symbol; mail.', 'lettera', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mother', 'A female parent.', 'modor', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('answer', 'A reply; to reply.', 'andswaru', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('found', 'Past of find.', 'findan', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('study', 'To learn; to look at carefully.', 'studium', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('still', 'Not moving; even so.', 'stille', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('learn', 'To gain knowledge.', 'leornian', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('should', 'Ought to; past of shall.', 'sceolde', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('America', 'The continent or the USA.', 'America', 'Latin', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('world', 'The earth and all people.', 'weorold', 'Old English', 'Year 4', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('high', 'Far above the ground.', 'heah', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('every', 'Each one.', 'æfre ælc', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('near', 'Close to.', 'near', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('add', 'To put with something else.', 'addere', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('food', 'What people and animals eat.', 'foda', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('between', 'In the space that separates two.', 'betweonum', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('own', 'Belonging to oneself.', 'agen', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('below', 'Under; lower than.', 'bilogan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('country', 'A nation; the countryside.', 'contrata', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('plant', 'A living thing that grows from the ground.', 'plante', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('last', 'Coming after all others.', 'latost', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('school', 'A place for learning.', 'scol', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('father', 'A male parent.', 'fæder', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('keep', 'To have and not give away.', 'cepan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('tree', 'A tall plant with a trunk and branches.', 'treo', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('never', 'Not ever.', 'næfre', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('start', 'To begin.', 'styrtan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('city', 'A large town.', 'civitas', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('earth', 'The planet we live on; soil.', 'eorthe', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('eyes', 'The organs you see with.', 'eage', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('light', 'Brightness; not heavy.', 'leoht', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('thought', 'An idea; past of think.', 'thoht', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('head', 'The part of the body above the neck.', 'heafod', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('under', 'Below; beneath.', 'under', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('story', 'A tale or account.', 'historie', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('saw', 'Past of see; a cutting tool.', 'seon', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('left', 'Opposite of right; past of leave.', 'lyft', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('don''t', 'Do not.', 'do not', 'English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('few', 'A small number.', 'fea', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('while', 'A period of time; during.', 'hwil', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('along', 'From one end to the other.', 'andlang', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('might', 'Past of may; power.', 'miht', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('close', 'Near; to shut.', 'clos', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('something', 'Some thing; a thing.', 'something', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('seem', 'To appear to be.', 'seman', 'Old Norse', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('next', 'Coming immediately after.', 'niehsta', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hard', 'Solid; difficult.', 'heard', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('open', 'Not closed; to make open.', 'open', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('example', 'Something that shows what others are like.', 'exemplum', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('begin', 'To start.', 'beginnan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('life', 'The state of being alive.', 'lif', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('always', 'Every time; forever.', 'ealne weg', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('those', 'Those ones there.', 'thas', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('both', 'The two; each of two.', 'ba', 'Old Norse', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('paper', 'Material for writing on.', 'papyrus', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('together', 'With each other.', 'togædere', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('got', 'Past of get.', 'getan', 'Old Norse', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('group', 'A set of people or things.', 'groupe', 'French', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('often', 'Many times.', 'oft', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('run', 'To move fast on foot.', 'rinnan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('important', 'Meaning a lot; serious.', 'importans', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('until', 'Up to the time of.', 'til', 'Old Norse', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('children', 'More than one child.', 'cild', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('side', 'The edge or face of something.', 'side', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('feet', 'More than one foot.', 'fet', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('car', 'A vehicle with wheels.', 'carra', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mile', 'A unit of distance.', 'mil', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('night', 'The dark part of the day.', 'niht', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('walk', 'To move on foot.', 'wealcan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('white', 'The colour of snow.', 'hwit', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sea', 'The salt water that covers much of the earth.', 'sæ', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('began', 'Past of begin.', 'beginnan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('grow', 'To get bigger.', 'growan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('took', 'Past of take.', 'tacan', 'Old Norse', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('river', 'A large stream of water.', 'river', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('four', 'The number 4.', 'feower', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('carry', 'To take from one place to another.', 'carier', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('state', 'A condition; a region of a country.', 'status', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('once', 'One time; in the past.', 'anes', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('book', 'Written or printed pages bound together.', 'boc', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('hear', 'To notice sound.', 'hieran', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('stop', 'To end movement or action.', 'stoppian', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('without', 'Not having.', 'withutan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('second', 'Next after first; a unit of time.', 'secundus', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('later', 'After a time.', 'lat', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('miss', 'To fail to hit or meet.', 'missan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('idea', 'A thought or plan.', 'idea', 'Greek', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('enough', 'As much as needed.', 'genog', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('eat', 'To take in food.', 'etan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('face', 'The front of the head.', 'facies', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('watch', 'To look at; a timepiece.', 'wæccan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('far', 'At a great distance.', 'feorr', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('Indian', 'From or relating to India.', 'India', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('real', 'Actually existing; not fake.', 'realis', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('almost', 'Nearly.', 'eallmæst', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('let', 'To allow.', 'lætan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('above', 'Higher than.', 'abufan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('girl', 'A female child.', 'gyrel', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('sometimes', 'From time to time.', 'some + times', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('mountains', 'Very high hills.', 'mont', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('cut', 'To divide with a sharp tool.', 'cyttan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('young', 'Not old; early in life.', 'geong', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('talk', 'To speak.', 'talian', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('soon', 'In a short time.', 'sona', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('list', 'A series of items written down.', 'liste', 'French', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('song', 'Music with words to sing.', 'sang', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('being', 'A living thing; existence.', 'beon', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('leave', 'To go away from.', 'læfan', 'Old English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('family', 'Parents and their children.', 'familia', 'Latin', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}'),
  ('it''s', 'It is; it has.', 'it is', 'English', 'Year 5', 'High-frequency word', '{}', '{}', 'Example sentence to be updated by teacher.', '{}')
ON CONFLICT (word) DO NOTHING;
